const fudalist = [
    {
        no:   0,
        left: null,
        center: null,
        right: null,
        initial: "序",
        kimariji: "(序歌)",
        kaminoku: "",
        shimonoku: "<span class='num'>序歌</span><label for='fuda'><ruby><rb>難波津</rb><rp>《</rp><rt>なにわず</rt><rp>》</rp></ruby>にー<ruby><rb>咲</rb><rp>《</rp><rt>さ</rt><rp>》</rp></ruby>くやこの<ruby><rb>花</rb><rp>《</rp><rt>はな</rt><rp>》</rp></ruby>ー<br>　　　　　ふゆごもーりー</label>",
    },
    {
        no:   0,
        left: null,
        center: null,
        right: null,
        initial: "序",
        kimariji: "(序歌)",
        kaminoku: "<span class='num'>序歌</span><label for='fuda'>いまをー<ruby><rb>春</rb><rp>《</rp><rt>はる</rt><rp>》</rp></ruby>べとー<br>　　　<ruby><rb>咲</rb><rp>《</rp><rt>さ</rt><rp>》</rp></ruby>くやこのーはなー</label>",
        shimonoku: "<span class='num'>序歌</span><label for='fuda'>いまをー<ruby><rb>春</rb><rp>《</rp><rt>はる</rt><rp>》</rp></ruby>べとー<br>　　　<ruby><rb>咲</rb><rp>《</rp><rt>さ</rt><rp>》</rp></ruby>くやこのーはなー</label>",
    },
    {
        no:  87,
        left: "キ",
        center: "シ",
        right: "ナ",
        initial: "1字",
        kimariji: "む",
        kaminoku: "<label for='fuda'><font color='red'>む</font>ら<ruby><rb>雨</rb><rp>（</rp><rt>さめ</rt><rp>）</rp></ruby>のー<ruby><rb>露</rb><rp>（</rp><rt>つゆ</rt><rp>）</rp></ruby>もまだ<ruby><rb>干</rb><rp>（</rp><rt>ひ</rt><rp>）</rp></ruby>ぬー<br>　　　　　　まきの<ruby><rb>葉</rb><rp>（</rp><rt>は</rt><rp>）</rp></ruby>ーにー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>霧</rb><rp>（</rp><rt>きり</rt><rp>）</rp></ruby>ーたちのぼるー<br>　　　<ruby><rb>秋</rb><rp>（</rp><rt>あき</rt><rp>）</rp></ruby>の<ruby><rb>夕</rb><rp>（</rp><rt>ゆー</rt><rp>）</rp></ruby>ーぐれー</label>",
    },
    {
        no:  18,
        left: "ク",
        center: "セ",
        right: "ヌ",
        initial: "1字",
        kimariji: "す",
        kaminoku: "<label for='fuda'><font color='red'>す</font>みの<ruby><rb>江</rb><rp>（</rp><rt>え</rt><rp>）</rp></ruby>のー<ruby><rb>岸</rb><rp>（</rp><rt>きし</rt><rp>）</rp></ruby>に<ruby><rb>寄</rb><rp>（</rp><rt>よ</rt><rp>）</rp></ruby>る<ruby><rb>波</rb><rp>（</rp><rt>なみ</rt><rp>）</rp></ruby>ー<br>　　　　　　よるさ<ruby><rb>へ</rb><rp>（</rp><rt>え</rt><rp>）</rp></ruby>ーやー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>夢</rb><rp>（</rp><rt>ゆめ</rt><rp>）</rp></ruby>のーかよ<ruby><rb>ひ</rb><rp>（</rp><rt>い</rt><rp>）</rp><rb>路</rb><rp>（</rp><rt>じ</rt><rp>）</rp></ruby>ー<br>　　　<ruby><rb>人</rb><rp>（</rp><rt>ひと</rt><rp>）</rp><rb>目</rb><rp>（</rp><rt>め</rt><rp>）</rp><rb>避</rb><rp>（</rp><rt>よ</rt><rp>）</rp></ruby>くーら<ruby><rb>む</rb><rp>（</rp><rt>ん</rt><rp>）</rp></ruby>ー</label>",
    },
    {
        no:  57,
        left: "エ",
        center: "ト",
        right: "ハ",
        initial: "1字",
        kimariji: "め",
        kaminoku: "<label for='fuda'><font color='red'>め</font>ぐりあ<ruby><rb>ひ</rb><rp>（</rp><rt>い</rt><rp>）</rp></ruby>てー<ruby><rb>見</rb><rp>（</rp><rt>み</rt><rp>）</rp></ruby>しやそれともー　<br>　　　　　　わかぬまーにー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>雲</rb><rp>（</rp><rt>くも</rt><rp>）</rp></ruby>がくれーにしー<br>　　　<ruby><rb>夜</rb><rp>（</rp><rt>よ</rt><rp>）</rp><rb>半</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>の<ruby><rb>月</rb><rp>（</rp><rt>つき</rt><rp>）</rp></ruby>ーかなー</label>",
    },
    {
        no:  22,
        left: "オ",
        center: "テ",
        right: "フ",
        initial: "1字",
        kimariji: "ふ",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>吹</rb><rp>（</rp><rt>ふ</rt><rp>）</rp></ruby></font>くからにー<ruby><rb>秋</rb><rp>（</rp><rt>あき</rt><rp>）</rp></ruby>の<ruby><rb>草</rb><rp>（</rp><rt>くさ</rt><rp>）</rp><rb>木</rb><rp>（</rp><rt>き</rt><rp>）</rp></ruby>のー<br>　　　　　　し<ruby><rb>を</rb><rp>（</rp><rt>お</rt><rp>）</rp></ruby>るれーばー</label>",
        shimonoku: "<label for='fuda'>むべー<ruby><rb>山</rb><rp>（</rp><rt>やま</rt><rp>）</rp><rb>風</rb><rp>（</rp><rt>かぜ</rt><rp>）</rp></ruby>をー<br>　　　<ruby><rb>嵐</rb><rp>（</rp><rt>あらし</rt><rp>）</rp></ruby>と<ruby><rb>い</rb><rp>（</rp><rt>ゆ</rt><rp>）</rp><rb>ふ</rb><rp>（</rp><rt>ー</rt><rp>）</rp></ruby>ーら<ruby><rb>む</rb><rp>（</rp><rt>ん</rt><rp>）</rp></ruby>ー</label>",
    },
    {
        no:  70,
        left: "ウ",
        center: "シ",
        right: "ホ",
        initial: "1字",
        kimariji: "さ",
        kaminoku: "<label for='fuda'><font color='red'>さ</font>びしさにー<ruby><rb>宿</rb><rp>（</rp><rt>やど</rt><rp>）</rp></ruby>をたち<ruby><rb>出</rb><rp>（</rp><rt>い</rt><rp>）</rp></ruby>でてー<br>　　　　　　ながむれーばー</label>",
        shimonoku: "<label for='fuda'>い<ruby><rb>づ</rb><rp>（</rp><rt>ず</rt><rp>）</rp></ruby>こもーおなじー<br>　　　<ruby><rb>秋</rb><rp>（</rp><rt>あき</rt><rp>）</rp></ruby>の<ruby><rb>夕</rb><rp>（</rp><rt>ゆー</rt><rp>）</rp></ruby>ーぐれー</label>",
    },
    {
        no:  81,
        left: "コ",
        center: "ス",
        right: "ネ",
        initial: "1字",
        kimariji: "ほ",
        kaminoku: "<label for='fuda'><font color='red'>ほ</font>ととぎすー<ruby><rb>鳴</rb><rp>（</rp><rt>な</rt><rp>）</rp></ruby>きつる<ruby><rb>方</rb><rp>（</rp><rt>かた</rt><rp>）</rp></ruby>をー<br>　　　　　　ながむれーばー</label>",
        shimonoku: "<label for='fuda'>ただーありあけのー<br>　　　<ruby><rb>月</rb><rp>（</rp><rt>つき</rt><rp>）</rp></ruby>ぞ<ruby><rb>残</rb><rp>（</rp><rt>のこ</rt><rp>）</rp></ruby>ーれるー</label>",
    },
    {
        no:  77,
        left: "カ",
        center: "サ",
        right: "ニ",
        initial: "1字",
        kimariji: "せ",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>瀬</rb><rp>（</rp><rt>せ</rt><rp>）</rp></ruby></font>をはやみー<ruby><rb>岩</rb><rp>（</rp><rt>いわ</rt><rp>）</rp></ruby>にせかるるー<br>　　　　　　<ruby><rb>滝</rb><rp>（</rp><rt>たき</rt><rp>）</rp><rb>川</rb><rp>（</rp><rt>がわ</rt><rp>）</rp></ruby>ーのー</label>",
        shimonoku: "<label for='fuda'>われてもー<ruby><rb>末</rb><rp>（</rp><rt>すえ</rt><rp>）</rp></ruby>にー<br>　　　あ<ruby><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp><rb>む</rb><rp>（</rp><rt>ん</rt><rp>）</rp></ruby>とぞー<ruby><rb>思</rb><rp>（</rp><rt>おも</rt><rp>）</rp><rb>ふ</rb><rp>（</rp><rt>(お)</rt><rp>）</rp></ruby>ー</label>",
    },
    {
        no:  74,
        left: "ケ",
        center: "セ",
        right: "ナ",
        initial: "う",
        kimariji: "うか",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>憂</rb><rp>（</rp><rt>う</rt><rp>）</rp></ruby>か</font>りけるー<ruby><rb>人</rb><rp>（</rp><rt>ひと</rt><rp>）</rp></ruby>を<ruby><rb>初</rb><rp>（</rp><rt>はつ</rt><rp>）</rp><rb>瀬</rb><rp>（</rp><rt>せ</rt><rp>）</rp></ruby>のー<br>　　　　　　<ruby><rb>山</rb><rp>（</rp><rt>やま</rt><rp>）</rp></ruby>おろーしー</label>",
        shimonoku: "<label for='fuda'>はげしかれーと<ruby><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ー<br>　　　<ruby><rb>祈</rb><rp>（</rp><rt>いの</rt><rp>）</rp></ruby>らぬーものをー</label>",
    },
    {
        no:  65,
        left: "ア",
        center: "テ",
        right: "ネ",
        initial: "う",
        kimariji: "うら",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>恨</rb><rp>（</rp><rt>うら</rt><rp>）</rp></ruby></font>みわびーほさぬ<ruby><rb>袖</rb><rp>（</rp><rt>そで</rt><rp>）</rp></ruby>だにー<br>　　　　　　あるものーをー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>恋</rb><rp>（</rp><rt>こい</rt><rp>）</rp></ruby>にー<ruby><rb>朽</rb><rp>（</rp><rt>く</rt><rp>）</rp></ruby>ちな<ruby><rb>む</rb><rp>（</rp><rt>ん</rt><rp>）</rp></ruby>ー<br>　　　<ruby><rb>名</rb><rp>（</rp><rt>な</rt><rp>）</rp></ruby>こそ<ruby><rb>惜</rb><rp>（</rp><rt>お</rt><rp>）</rp></ruby>しーけれー</label>",
    },
    {
        no:  23,
        left: "イ",
        center: "ス",
        right: "ノ",
        initial: "つ",
        kimariji: "つき",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>月</rb><rp>（</rp><rt>つき</rt><rp>）</rp></ruby></font><ruby><rb>見</rb><rp>（</rp><rt>み</rt><rp>）</rp></ruby>ればーち<ruby><rb>ぢ</rb><rp>（</rp><rt>じ</rt><rp>）</rp></ruby>に<ruby><rb>物</rb><rp>（</rp><rt>もの</rt><rp>）</rp></ruby>こそー<br>　　　　　　<ruby><rb>悲</rb><rp>（</rp><rt>かな</rt><rp>）</rp></ruby>しけーれー</label>",
        shimonoku: "<label for='fuda'>わが<ruby><rb>身</rb><rp>（</rp><rt>み</rt><rp>）</rp></ruby>ーひとつのー<br>　　　<ruby><rb>秋</rb><rp>（</rp><rt>あき</rt><rp>）</rp></ruby>に<ruby><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>あらーねどー</label>",
    },
    {
        no:  13,
        left: "カ",
        center: "ソ",
        right: "フ",
        initial: "つ",
        kimariji: "つく",
        kaminoku: "<label for='fuda'><font color='red'>つく</font>ばねのー<ruby><rb>峰</rb><rp>（</rp><rt>みね</rt><rp>）</rp></ruby>よりおつるー<br>　　　　　　みなのー<ruby><rb>川</rb><rp>（</rp><rt>がわ</rt><rp>）</rp></ruby>ー</label>",
        shimonoku: "<label for='fuda'>こ<ruby><rb>ひ</rb><rp>（</rp><rt>い</rt><rp>）</rp></ruby>ぞーつもりてー<br>　　　<ruby><rb>淵</rb><rp>（</rp><rt>ふち</rt><rp>）</rp></ruby>となりーぬるー</label>",
    },
    {
        no:  40,
        left: "コ",
        center: "ト",
        right: "ヘ",
        initial: "し",
        kimariji: "しの",
        kaminoku: "<label for='fuda'><font color='red'>しの</font>ぶれどー<ruby><rb>色</rb><rp>（</rp><rt>いろ</rt><rp>）</rp></ruby>に<ruby><rb>出</rb><rp>（</rp><rt>い</rt><rp>）</rp></ruby>でにけりー<br>　　　　　　わが<ruby><rb>恋</rb><rp>（</rp><rt>こい</rt><rp>）</rp></ruby>ー<ruby><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>物</rb><rp>（</rp><rt>もの</rt><rp>）</rp></ruby>やー<ruby><rb>思</rb><rp>（</rp><rt>おも</rt><rp>）</rp><rb>ふ</rb><rp>（</rp><rt>ー</rt><rp>）</rp></ruby>とー<br>　　　<ruby><rb>人</rb><rp>（</rp><rt>ひと</rt><rp>）</rp></ruby>のと<ruby><rb>ふ</rb><rp>（</rp><rt>ー</rt><rp>）</rp></ruby>ーまでー</label>",
    },
    {
        no:  37,
        left: "イ",
        center: "チ",
        right: "ハ",
        initial: "し",
        kimariji: "しら",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>白</rb><rp>（</rp><rt>しら</rt><rp>）</rp></ruby></font><ruby><rb>露</rb><rp>（</rp><rt>つゆ</rt><rp>）</rp></ruby>にー<ruby><rb>風</rb><rp>（</rp><rt>かぜ</rt><rp>）</rp></ruby>の<ruby><rb>吹</rb><rp>（</rp><rt>ふ</rt><rp>）</rp></ruby>きしくー<br>　　　　　　<ruby><rb>秋</rb><rp>（</rp><rt>あき</rt><rp>）</rp></ruby>の<ruby><rb>野</rb><rp>（</rp><rt>の</rt><rp>）</rp></ruby>ーはー</label>",
        shimonoku: "<label for='fuda'>つらぬきーとめぬー<br>　　　<ruby><rb>玉</rb><rp>（</rp><rt>たま</rt><rp>）</rp></ruby>ぞ<ruby><rb>散</rb><rp>（</rp><rt>ち</rt><rp>）</rp></ruby>りーけるー</label>",
    },
    {
        no:  66,
        left: "オ",
        center: "テ",
        right: "ヒ",
        initial: "も",
        kimariji: "もろ",
        kaminoku: "<label for='fuda'><font color='red'>もろ</font>ともにーあ<ruby><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>れと<ruby><rb>思</rb><rp>（</rp><rt>おも</rt><rp>）</rp><rb>へ</rb><rp>（</rp><rt>え</rt><rp>）</rp></ruby>ー<br>　　　　　　<ruby><rb>山</rb><rp>（</rp><rt>やま</rt><rp>）</rp></ruby>ざくーらー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>花</rb><rp>（</rp><rt>はな</rt><rp>）</rp></ruby>よりーほかにー<br>　　　しる<ruby><rb>人</rb><rp>（</rp><rt>ひと</rt><rp>）</rp></ruby>もーなしー</label>",
    },
    {
        no: 100,
        left: "ケ",
        center: "サ",
        right: "ホ",
        initial: "も",
        kimariji: "もも",
        kaminoku: "<label for='fuda'><font color='red'>もも</font>しきやー<ruby><rb>古</rb><rp>（</rp><rt>ふる</rt><rp>）</rp></ruby>き<ruby><rb>軒</rb><rp>（</rp><rt>のき</rt><rp>）</rp><rb>端</rb><rp>（</rp><rt>ば</rt><rp>）</rp></ruby>のー<br>　　　　　　しのぶにーもー</label>",
        shimonoku: "<label for='fuda'>な<ruby><rb>ほ</rb><rp>（</rp><rt>お</rt><rp>）</rp></ruby>ーあまりあるー<br>　　　<ruby><rb>昔</rb><rp>（</rp><rt>むかし</rt><rp>）</rp></ruby>なりーけりー</label>",
    },
    {
        no:  71,
        left: "ア",
        center: "シ",
        right: "ニ",
        initial: "ゆ",
        kimariji: "ゆう",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>夕</rb><rp>（</rp><rt>ゆ(う)</rt><rp>）</rp></ruby></font>さればー<ruby><rb>門</rb><rp>（</rp><rt>かど</rt><rp>）</rp><rb>田</rb><rp>（</rp><rt>た</rt><rp>）</rp></ruby>の<ruby><rb>稲</rb><rp>（</rp><rt>いな</rt><rp>）</rp><rb>葉</rb><rp>（</rp><rt>ば</rt><rp>）</rp></ruby>ー<br>　　　　　　おと<ruby><rb>づ</rb><rp>（</rp><rt>ず</rt><rp>）</rp></ruby>れーてー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>芦</rb><rp>（</rp><rt>あし</rt><rp>）</rp></ruby>のーまろやにー<br>　　　<ruby><rb>秋</rb><rp>（</rp><rt>あき</rt><rp>）</rp><rb>風</rb><rp>（</rp><rt>かぜ</rt><rp>）</rp></ruby>ぞー<ruby><rb>吹</rb><rp>（</rp><rt>ふ</rt><rp>）</rp></ruby>くー</label>",
    },
    {
        no:  46,
        left: "ク",
        center: "ツ",
        right: "ヌ",
        initial: "ゆ",
        kimariji: "ゆら",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>由</rb><rp>（</rp><rt>ゆ</rt><rp>）</rp><rb>良</rb><rp>（</rp><rt>ら</rt><rp>）</rp></ruby></font>のとをーわたる<ruby><rb>船</rb><rp>（</rp><rt>ふな</rt><rp>）</rp><rb>人</rb><rp>（</rp><rt>びと</rt><rp>）</rp></ruby>ー<br>　　　　　　か<ruby><rb>ぢ</rb><rp>（</rp><rt>じ</rt><rp>）</rp></ruby>をーたえー</label>",
        shimonoku: "<label for='fuda'>ゆく<ruby><rb>へ</rb><rp>（</rp><rt>え</rt><rp>）</rp></ruby>もーしらぬー<br>　　　<ruby><rb>恋</rb><rp>（</rp><rt>こい</rt><rp>）</rp></ruby>の<ruby><rb>道</rb><rp>（</rp><rt>みち</rt><rp>）</rp></ruby>ーかなー</label>",
    },
    {
        no:  61,
        left: "エ",
        center: "セ",
        right: "ニ",
        initial: "い",
        kimariji: "いに",
        kaminoku: "<label for='fuda'><font color='red'>いに</font>し<ruby><rb>へ</rb><rp>（</rp><rt>え</rt><rp>）</rp></ruby>のー<ruby><rb>奈</rb><rp>（</rp><rt>な</rt><rp>）</rp><rb>良</rb><rp>（</rp><rt>ら</rt><rp>）</rp></ruby>の<ruby><rb>都</rb><rp>（</rp><rt>みやこ</rt><rp>）</rp></ruby>のー<br>　　　　　　<ruby><rb>八</rb><rp>（</rp><rt>や</rt><rp>）</rp><rb>重</rb><rp>（</rp><rt>え</rt><rp>）</rp></ruby>ざくーらー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>けふ</rb><rp>（</rp><rt>きょー</rt><rp>）</rp></ruby>ー<ruby><rb>九重</rb><rp>（</rp><rt>ここのえ</rt><rp>）</rp></ruby>にー<br>　　　に<ruby><rb>ほ</rb><rp>（</rp><rt>お</rt><rp>）</rp><rb>ひ</rb><rp>（</rp><rt>い</rt><rp>）</rp></ruby>ぬるーかなー</label>",
    },
    {
        no:  63,
        left: "ア",
        center: "シ",
        right: "ノ",
        initial: "い",
        kimariji: "いまは",
        kaminoku: "<label for='fuda'><font color='red'>いま<ruby><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby></font>ただー<ruby><rb>思</rb><rp>（</rp><rt>おも</rt><rp>）</rp><rb>ひ</rb><rp>（</rp><rt>い</rt><rp>）</rp><rb>絶</rb><rp>（</rp><rt>た</rt><rp>）</rp></ruby>えな<ruby><rb>む</rb><rp>（</rp><rt>ん</rt><rp>）</rp></ruby>とー<br>　　　　　　ばかりーをー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>人</rb><rp>（</rp><rt>ひと</rt><rp>）</rp><rb>づ</rb><rp>（</rp><rt>ず</rt><rp>）</rp></ruby>てーならでー<br>　　　<ruby><rb>言</rb><rp>（</rp><rt>ゆ</rt><rp>）</rp><rb>ふ</rb><rp>（</rp><rt>ー</rt><rp>）</rp></ruby>よしーもがなー</label>",
    },
    {
        no:  21,
        left: "ケ",
        center: "ツ",
        right: "ヒ",
        initial: "い",
        kimariji: "いまこ",
        kaminoku: "<label for='fuda'><font color='red'>いま<ruby><rb>来</rb><rp>（</rp><rt>こ</rt><rp>）</rp></ruby></font><ruby><rb>む</rb><rp>（</rp><rt>ん</rt><rp>）</rp></ruby>とーい<ruby><rb>ひ</rb><rp>（</rp><rt>ー</rt><rp>）</rp></ruby>しばかりにー<br>　　　　　　<ruby><rb>長</rb><rp>（</rp><rt>なが</rt><rp>）</rp><rb>月</rb><rp>（</rp><rt>つき</rt><rp>）</rp></ruby>ーのー</label>",
        shimonoku: "<label for='fuda'>ありあけのー<ruby><rb>月</rb><rp>（</rp><rt>つき</rt><rp>）</rp></ruby>をー<br>　　<ruby><rb>待</rb><rp>（</rp><rt>ま</rt><rp>）</rp></ruby>ち<ruby><rb>出</rb><rp>（</rp><rt>い</rt><rp>）</rp></ruby>でつるーかなー</label>",
    },
    {
        no:  17,
        left: "キ",
        center: "サ",
        right: "ヘ",
        initial: "ち",
        kimariji: "ちは",
        kaminoku: "<label for='fuda'><font color='red'>ちは</font>やぶるー<ruby><rb>神</rb><rp>（</rp><rt>かみ</rt><rp>）</rp><rb>代</rb><rp>（</rp><rt>よ</rt><rp>）</rp></ruby>もきかずー<br>　　　　　　<ruby><rb>竜</rb><rp>（</rp><rt>たつ</rt><rp>）</rp><rb>田</rb><rp>（</rp><rt>た</rt><rp>）</rp></ruby>ー<ruby><rb>川</rb><rp>（</rp><rt>がわ</rt><rp>）</rp></ruby>ー</label>",
        shimonoku: "<label for='fuda'>からーくれな<ruby><rb>ゐ</rb><rp>（</rp><rt>い</rt><rp>）</rp></ruby>にー<br>　　　<ruby><rb>水</rb><rp>（</rp><rt>みず</rt><rp>）</rp></ruby>くくるーと<ruby><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ー</label>",
    },
    {
        no:  42,
        left: "ク",
        center: "ト",
        right: "ホ",
        initial: "ち",
        kimariji: "ちぎりき",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>契</rb><rp>（</rp><rt>ちぎ</rt><rp>）</rp></ruby>りき</font>なーかたみに<ruby><rb>袖</rb><rp>（</rp><rt>そで</rt><rp>）</rp></ruby>をー<br>　　　　　　しぼりーつつー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>末</rb><rp>（</rp><rt>すえ</rt><rp>）</rp></ruby>のー<ruby><rb>松</rb><rp>（</rp><rt>まつ</rt><rp>）</rp><rb>山</rb><rp>（</rp><rt>やま</rt><rp>）</rp></ruby>ー<br>　　　<ruby><rb>波</rb><rp>（</rp><rt>なみ</rt><rp>）</rp></ruby>こさじーと<ruby><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ー</label>",
    },
    {
        no:  75,
        left: "オ",
        center: "タ",
        right: "ヌ",
        initial: "ち",
        kimariji: "ちぎりお",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>契</rb><rp>（</rp><rt>ちぎ</rt><rp>）</rp></ruby>りお</font>きしーさせもが<ruby><rb>露</rb><rp>（</rp><rt>つゆ</rt><rp>）</rp></ruby>をー<br>　　　　　　いのちにーてー</label>",
        shimonoku: "<label for='fuda'>あ<ruby><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>れー<ruby><rb>今年</rb><rp>（</rp><rt>ことし</rt><rp>）</rp></ruby>のー<br>　　　<ruby><rb>秋</rb><rp>（</rp><rt>あき</rt><rp>）</rp></ruby>もいぬーめりー</label>",
    },
    {
        no:  33,
        left: "ウ",
        center: "ト",
        right: "ネ",
        initial: "ひ",
        kimariji: "ひさ",
        kaminoku: "<label for='fuda'><font color='red'>ひさ</font>かたのー<ruby><rb>光</rb><rp>（</rp><rt>ひかり</rt><rp>）</rp></ruby>のどけきー<br>　　　　　　<ruby><rb>春</rb><rp>（</rp><rt>はる</rt><rp>）</rp></ruby>の<ruby><rb>日</rb><rp>（</rp><rt>ひ</rt><rp>）</rp></ruby>ーにー</label>",
        shimonoku: "<label for='fuda'>し<ruby><rb>づ</rb><rp>（</rp><rt>ず</rt><rp>）</rp><rb>心</rb><rp>（</rp><rt>ごころ</rt><rp>）</rp></ruby>ーなくー<br>　　　<ruby><rb>花</rb><rp>（</rp><rt>はな</rt><rp>）</rp></ruby>の<ruby><rb>散</rb><rp>（</rp><rt>ち</rt><rp>）</rp></ruby>るーら<ruby><rb>む</rb><rp>（</rp><rt>ん</rt><rp>）</rp></ruby>ー</label>",
    },
    {
        no:  35,
        left: "イ",
        center: "ス",
        right: "フ",
        initial: "ひ",
        kimariji: "ひとは",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>人</rb><rp>（</rp><rt>ひと</rt><rp>）</rp><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby></font>いさー<ruby><rb>心</rb><rp>（</rp><rt>こころ</rt><rp>）</rp></ruby>もしらずー<br>　　　　　　ふるさとー<ruby><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>花</rb><rp>（</rp><rt>はな</rt><rp>）</rp></ruby>ぞー<ruby><rb>昔</rb><rp>（</rp><rt>むかし</rt><rp>）</rp></ruby>のー<br>　　　<ruby><rb>香</rb><rp>（</rp><rt>か</rt><rp>）</rp></ruby>にに<ruby><rb>ほ</rb><rp>（</rp><rt>お</rt><rp>）</rp><rb>ひ</rb><rp>（</rp><rt>い</rt><rp>）</rp></ruby>ーけるー</label>",
    },
    {
        no:  99,
        left: "カ",
        center: "テ",
        right: "ハ",
        initial: "ひ",
        kimariji: "ひとも",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>人</rb><rp>（</rp><rt>ひと</rt><rp>）</rp></ruby>も</font><ruby><rb>を</rb><rp>（</rp><rt>お</rt><rp>）</rp></ruby>しー<ruby><rb>人</rb><rp>（</rp><rt>ひと</rt><rp>）</rp></ruby>もうらめしー<br>　　　　　　あ<ruby><rb>ぢ</rb><rp>（</rp><rt>じ</rt><rp>）</rp></ruby>きなーくー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>世</rb><rp>（</rp><rt>よ</rt><rp>）</rp></ruby>をー<ruby><rb>思</rb><rp>（</rp><rt>おも</rt><rp>）</rp><rb>ふ</rb><rp>（</rp><rt>ー</rt><rp>）</rp></ruby>ゆ<ruby><rb>ゑ</rb><rp>（</rp><rt>え</rt><rp>）</rp></ruby>にー<br>　　　<ruby><rb>物</rb><rp>（</rp><rt>もの</rt><rp>）</rp><rb>思</rb><rp>（</rp><rt>おも</rt><rp>）</rp><rb>ふ</rb><rp>（</rp><rt>ー</rt><rp>）</rp></ruby>ー<ruby><rb>身</rb><rp>（</rp><rt>み</rt><rp>）</rp><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ー</label>",
    },
    {
        no:  91,
        left: "コ",
        center: "サ",
        right: "ヌ",
        initial: "き",
        kimariji: "きり",
        kaminoku: "<label for='fuda'><font color='red'>きり</font>ぎりすー<ruby><rb>鳴</rb><rp>（</rp><rt>な</rt><rp>）</rp></ruby>くや<ruby><rb>霜</rb><rp>（</rp><rt>しも</rt><rp>）</rp><rb>夜</rb><rp>（</rp><rt>よ</rt><rp>）</rp></ruby>のー<br>　　　　　　さむしろーにー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>衣</rb><rp>（</rp><rt>ころも</rt><rp>）</rp></ruby>ーかたしきー<br>　　　ひとりかもー<ruby><rb>寝</rb><rp>（</rp><rt>ね</rt><rp>）</rp><rb>む</rb><rp>（</rp><rt>ん</rt><rp>）</rp></ruby>ー</label>",
    },
    {
        no:  15,
        left: "ア",
        center: "セ",
        right: "ホ",
        initial: "き",
        kimariji: "きみ・は",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>君</rb><rp>（</rp><rt>きみ</rt><rp>）</rp></ruby>がためは</font>るのー<ruby><rb>野</rb><rp>（</rp><rt>の</rt><rp>）</rp></ruby>にいでてー<br>　　　　　　<ruby><rb>若</rb><rp>（</rp><rt>わか</rt><rp>）</rp><rb>菜</rb><rp>（</rp><rt>な</rt><rp>）</rp></ruby>ーつむー</label>",
        shimonoku: "<label for='fuda'>わがー<ruby><rb>衣</rb><rp>（</rp><rt>ころも</rt><rp>）</rp><rb>手</rb><rp>（</rp><rt>で</rt><rp>）</rp></ruby>にー<br>　　　<ruby><rb>雪</rb><rp>（</rp><rt>ゆき</rt><rp>）</rp><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp><rb>降</rb><rp>（</rp><rt>ふ</rt><rp>）</rp></ruby>りーつつー</label>",
    },
    {
        no:  50,
        left: "エ",
        center: "ス",
        right: "ナ",
        initial: "き",
        kimariji: "きみ・お",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>君</rb><rp>（</rp><rt>きみ</rt><rp>）</rp></ruby>がため<ruby><rb>惜</rb><rp>（</rp><rt>お</rt><rp>）</rp></ruby></font>しからーざりしー<br>　　　　　　<ruby><rb>命</rb><rp>（</rp><rt>いのち</rt><rp>）</rp></ruby>ーさ<ruby><rb>へ</rb><rp>（</rp><rt>え</rt><rp>）</rp></ruby>ー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>長</rb><rp>（</rp><rt>なが</rt><rp>）</rp></ruby>くーもがなとー<br>　　　<ruby><rb>思</rb><rp>（</rp><rt>おも</rt><rp>）</rp><rb>ひ</rb><rp>（</rp><rt>い</rt><rp>）</rp></ruby>けるーかなー</label>",
    },
    {
        no:   2,
        left: "ウ",
        center: "セ",
        right: "ヒ",
        initial: "は",
        kimariji: "はるす",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>春</rb><rp>（</rp><rt>はる</rt><rp>）</rp><rb>過</rb><rp>（</rp><rt>す</rt><rp>）</rp></ruby></font>ぎてー<ruby><rb>夏</rb><rp>（</rp><rt>なつ</rt><rp>）</rp><rb>来</rb><rp>（</rp><rt>き</rt><rp>）</rp></ruby>にけらしー<br>　　　　　　<ruby><rb>白</rb><rp>（</rp><rt>しろ</rt><rp>）</rp><rb>妙</rb><rp>（</rp><rt>たえ</rt><rp>）</rp></ruby>ーのー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>衣</rb><rp>《</rp><rt>ころも</rt><rp>》</rp></ruby>ーほす<ruby><rb>てふ</rb><rp>《</rp><rt>ちょー</rt><rp>》</rp></ruby><br>　　　<ruby><rb>天</rb><rp>《</rp><rt>あま</rt><rp>》</rp></ruby>の<ruby><rb>香</rb><rp>（</rp><rt>か</rt><rp>）</rp><rb>具</rb><rp>（</rp><rt>ぐ</rt><rp>）</rp></ruby>ー<ruby><rb>山</rb><rp>《</rp><rt>やま</rt><rp>》</rp></ruby>ー</label>",
    },
    {
        no:  67,
        left: "オ",
        center: "チ",
        right: "ヘ",
        initial: "は",
        kimariji: "はるの",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>春</rb><rp>（</rp><rt>はる</rt><rp>）</rp></ruby>の</font><ruby><rb>夜</rb><rp>（</rp><rt>よ</rt><rp>）</rp></ruby>のーゆめばかりなるー<br>　　　　　　<ruby><rb>手枕</rb><rp>（</rp><rt>たまくら</rt><rp>）</rp></ruby>ーにー</label>",
        shimonoku: "<label for='fuda'>か<ruby><rb>ひ</rb><rp>（</rp><rt>い</rt><rp>）</rp></ruby>なくーたた<ruby><rb>む</rb><rp>（</rp><rt>ん</rt><rp>）</rp></ruby>ー<br>　　　<ruby><rb>名</rb><rp>（</rp><rt>な</rt><rp>）</rp></ruby>こそ<ruby><rb>を</rb><rp>（</rp><rt>お</rt><rp>）</rp></ruby>しーけれー</label>",
    },
    {
        no:  96,
        left: "ク",
        center: "タ",
        right: "ニ",
        initial: "は",
        kimariji: "はなさ",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>花</rb><rp>（</rp><rt>はな</rt><rp>）</rp></ruby>さ</font>そ<ruby><rb>ふ</rb><rp>（</rp><rt>ー</rt><rp>）</rp></ruby>ー<ruby><rb>嵐</rb><rp>（</rp><rt>あらし</rt><rp>）</rp></ruby>の<ruby><rb>庭</rb><rp>（</rp><rt>にわ</rt><rp>）</rp></ruby>のー<br>　　　　　　<ruby><rb>雪</rb><rp>（</rp><rt>ゆき</rt><rp>）</rp></ruby>ならーでー</label>",
        shimonoku: "<label for='fuda'>ふりゆくーもの<ruby><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ー<br>　　　わが<ruby><rb>身</rb><rp>（</rp><rt>み</rt><rp>）</rp></ruby>なりーけりー</label>",
    },
    {
        no:   9,
        left: "キ",
        center: "ツ",
        right: "ハ",
        initial: "は",
        kimariji: "はなの",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>花</rb><rp>（</rp><rt>はな</rt><rp>）</rp></ruby>の</font><ruby><rb>色</rb><rp>（</rp><rt>いろ</rt><rp>）</rp><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ーうつりにけりなー<br>　　　　　　いた<ruby><rb>づ</rb><rp>（</rp><rt>ず</rt><rp>）</rp></ruby>らーにー</label>",
        shimonoku: "<label for='fuda'>わが<ruby><rb>身</rb><rp>（</rp><rt>み</rt><rp>）</rp></ruby>ーよにふるー<br>　　　ながめせしーまにー</label>",
    },
    {
        no:  59,
        left: "カ",
        center: "ス",
        right: "ヘ",
        initial: "や",
        kimariji: "やす",
        kaminoku: "<label for='fuda'><font color='red'>やす</font>ら<ruby><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>でー<ruby><rb>寝</rb><rp>（</rp><rt>ね</rt><rp>）</rp></ruby>なましものをー<br>　　　　　　さ<ruby><rb>夜</rb><rp>（</rp><rt>よ</rt><rp>）</rp></ruby>ふけーてー</label>",
        shimonoku: "<label for='fuda'>かたぶくーまでのー<br>　　　<ruby><rb>月</rb><rp>（</rp><rt>つき</rt><rp>）</rp></ruby>をみしーかなー</label>",
    },
    {
        no:  47,
        left: "ウ",
        center: "サ",
        right: "フ",
        initial: "や",
        kimariji: "やえ",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>八</rb><rp>（</rp><rt>や</rt><rp>）</rp><rb>重</rb><rp>（</rp><rt>え</rt><rp>）</rp></ruby></font><ruby><rb>葎</rb><rp>（</rp><rt>むぐら</rt><rp>）</rp></ruby>ーしげれる<ruby><rb>宿</rb><rp>（</rp><rt>やど</rt><rp>）</rp></ruby>のー<br>　　　　　　さびしきーにー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>人</rb><rp>（</rp><rt>ひと</rt><rp>）</rp></ruby>こそー<ruby><rb>見</rb><rp>（</rp><rt>み</rt><rp>）</rp></ruby>えねー<br>　　　<ruby><rb>秋</rb><rp>（</rp><rt>あき</rt><rp>）</rp><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp><rb>来</rb><rp>（</rp><rt>き</rt><rp>）</rp></ruby>にーけりー</label>",
    },
    {
        no:  32,
        left: "コ",
        center: "テ",
        right: "ホ",
        initial: "や",
        kimariji: "やまが",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>山</rb><rp>（</rp><rt>やま</rt><rp>）</rp></ruby>が</font>わにー<ruby><rb>風</rb><rp>（</rp><rt>かぜ</rt><rp>）</rp></ruby>のかけたるー<br>　　　　　　しがらみー<ruby><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>流</rb><rp>（</rp><rt>なが</rt><rp>）</rp></ruby>れもーあ<ruby><rb>へ</rb><rp>（</rp><rt>え</rt><rp>）</rp></ruby>ぬー<br>　　　もみ<ruby><rb>ぢ</rb><rp>（</rp><rt>じ</rt><rp>）</rp></ruby>なりーけりー</label>",
    },
    {
        no:  28,
        left: "キ",
        center: "チ",
        right: "ネ",
        initial: "や",
        kimariji: "やまざ",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>山</rb><rp>（</rp><rt>やま</rt><rp>）</rp></ruby>ざ</font>と<ruby><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ー<ruby><rb>冬</rb><rp>（</rp><rt>ふゆ</rt><rp>）</rp></ruby>ぞさびしさー<br>　　　　　　まさりーけるー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>人</rb><rp>（</rp><rt>ひと</rt><rp>）</rp></ruby>めもー<ruby><rb>草</rb><rp>（</rp><rt>くさ</rt><rp>）</rp></ruby>もー<br>　　　かれぬと<ruby><rb>思</rb><rp>（</rp><rt>おも</rt><rp>）</rp></ruby>ー<ruby><rb>へ</rb><rp>（</rp><rt>え</rt><rp>）</rp></ruby>ばー</label>",
    },
    {
        no:  62,
        left: "イ",
        center: "セ",
        right: "ハ",
        initial: "よ",
        kimariji: "よを",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>夜</rb><rp>（</rp><rt>よ</rt><rp>）</rp><rb>を</rb><rp>（</rp><rt>(を)</rt><rp>）</rp></ruby></font>こめてー<ruby><rb>鳥</rb><rp>（</rp><rt>とり</rt><rp>）</rp></ruby>のそらねはー<br>　　　　　　はかるーともー</label>",
        shimonoku: "<label for='fuda'>よにー<ruby><rb>逢</rb><rp>（</rp><rt>おー</rt><rp>）</rp><rb>坂</rb><rp>（</rp><rt>さか</rt><rp>）</rp></ruby>のー<br>　　　<ruby><rb>関</rb><rp>（</rp><rt>せき</rt><rp>）</rp><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ゆるーさじー</label>",
    },
    {
        no:  85,
        left: "ケ",
        center: "ト",
        right: "ヒ",
        initial: "よ",
        kimariji: "よも",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>夜</rb><rp>（</rp><rt>よ</rt><rp>）</rp></ruby>も</font>すがらー<ruby><rb>物</rb><rp>（</rp><rt>もの</rt><rp>）</rp><rb>思</rb><rp>（</rp><rt>おも</rt><rp>）</rp><rb>ふ</rb><rp>（</rp><rt>ー</rt><rp>）</rp></ruby>ころはー<br>　　　　　　<ruby><rb>明</rb><rp>（</rp><rt>あ</rt><rp>）</rp></ruby>けやらーでー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>閨</rb><rp>（</rp><rt>ねや</rt><rp>）</rp></ruby>のーひまさ<ruby><rb>へ</rb><rp>（</rp><rt>え</rt><rp>）</rp></ruby>ー<br>　　　つれなかりーけりー</label>",
    },
    {
        no:  93,
        left: "エ",
        center: "ソ",
        right: "ノ",
        initial: "よ",
        kimariji: "よの・は",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>世</rb><rp>（</rp><rt>よ</rt><rp>）</rp></ruby>の<ruby><rb>中</rb><rp>（</rp><rt>なか</rt><rp>）</rp><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby></font>ーつねにもがもなー<br>　　　　　　なぎさー<ruby><rb>漕</rb><rp>（</rp><rt>こ</rt><rp>）</rp></ruby>ぐー</label>",
        shimonoku: "<label for='fuda'>あまのー<ruby><rb>小</rb><rp>（</rp><rt>お</rt><rp>）</rp><rb>舟</rb><rp>（</rp><rt>ぶね</rt><rp>）</rp></ruby>のー<br>　　　<ruby><rb>綱</rb><rp>（</rp><rt>つな</rt><rp>）</rp><rb>手</rb><rp>（</rp><rt>で</rt><rp>）</rp></ruby>かなーしもー</label>",
    },
    {
        no:  83,
        left: "オ",
        center: "タ",
        right: "ナ",
        initial: "よ",
        kimariji: "よの・よ",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>世</rb><rp>（</rp><rt>よ</rt><rp>）</rp></ruby>の<ruby><rb>中</rb><rp>（</rp><rt>なか</rt><rp>）</rp></ruby>よ</font>ー<ruby><rb>道</rb><rp>（</rp><rt>みち</rt><rp>）</rp></ruby>こそなけれー<br>　　　　　　<ruby><rb>思</rb><rp>（</rp><rt>おも</rt><rp>）</rp><rb>ひ</rb><rp>（</rp><rt>い</rt><rp>）</rp></ruby>ー<ruby><rb>入</rb><rp>（</rp><rt>い</rt><rp>）</rp></ruby>るー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>山</rb><rp>（</rp><rt>やま</rt><rp>）</rp></ruby>のー<ruby><rb>奥</rb><rp>（</rp><rt>おく</rt><rp>）</rp></ruby>にもー<br>　　　<ruby><rb>鹿</rb><rp>（</rp><rt>しか</rt><rp>）</rp></ruby>ぞ<ruby><rb>鳴</rb><rp>（</rp><rt>な</rt><rp>）</rp></ruby>くーなるー</label>",
    },
    {
        no:  51,
        left: "ウ",
        center: "タ",
        right: "ネ",
        initial: "か",
        kimariji: "かく",
        kaminoku: "<label for='fuda'><font color='red'>かく</font>とだにーえや<ruby><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>いぶきのー<br>　　　　　　さしもー<ruby><rb>草</rb><rp>（</rp><rt>ぐさ</rt><rp>）</rp></ruby>ー</label>",
        shimonoku: "<label for='fuda'>さしもーしらじなー<br>　　　もゆる<ruby><rb>思</rb><rp>（</rp><rt>おも</rt><rp>）</rp></ruby>ー<ruby><rb>ひ</rb><rp>（</rp><rt>い</rt><rp>）</rp></ruby>をー</label>",
    },
    {
        no:   6,
        left: "カ",
        center: "テ",
        right: "ナ",
        initial: "か",
        kimariji: "かさ",
        kaminoku: "<label for='fuda'><font color='red'>かさ</font>さぎのー<ruby><rb>渡</rb><rp>（</rp><rt>わた</rt><rp>）</rp></ruby>せる<ruby><rb>橋</rb><rp>（</rp><rt>はし</rt><rp>）</rp></ruby>にー<br>　　　　　　おく<ruby><rb>霜</rb><rp>（</rp><rt>しも</rt><rp>）</rp></ruby>ーのー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>白</rb><rp>（</rp><rt>しろ</rt><rp>）</rp></ruby>きをー<ruby><rb>見</rb><rp>（</rp><rt>み</rt><rp>）</rp></ruby>ればー<br>　　　<ruby><rb>夜</rb><rp>（</rp><rt>よ</rt><rp>）</rp></ruby>ぞふけにーけるー</label>",
    },
    {
        no:  98,
        left: "ク",
        center: "ト",
        right: "ヌ",
        initial: "か",
        kimariji: "かぜそ",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>風</rb><rp>（</rp><rt>かぜ</rt><rp>）</rp></ruby>そ</font>よぐーならの<ruby><rb>小</rb><rp>（</rp><rt>お</rt><rp>）</rp><rb>川</rb><rp>（</rp><rt>がわ</rt><rp>）</rp></ruby>のー<br>　　　　　　<ruby><rb>夕</rb><rp>（</rp><rt>ゆー</rt><rp>）</rp></ruby>ぐれー<ruby><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ー</label>",
        shimonoku: "<label for='fuda'>みそぎぞー<ruby><rb>夏</rb><rp>（</rp><rt>なつ</rt><rp>）</rp></ruby>のー<br>　　　しるしなりーけるー</label>",
    },
    {
        no:  48,
        left: "イ",
        center: "ソ",
        right: "ヒ",
        initial: "か",
        kimariji: "かぜを",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>風</rb><rp>（</rp><rt>かぜ</rt><rp>）</rp></ruby>を</font>いたみー<ruby><rb>岩</rb><rp>（</rp><rt>いわ</rt><rp>）</rp></ruby>うつ<ruby><rb>波</rb><rp>（</rp><rt>なみ</rt><rp>）</rp></ruby>のー<br>　　　　　　おのれーのみー</label>",
        shimonoku: "<label for='fuda'>くだけてー<ruby><rb>物</rb><rp>（</rp><rt>もの</rt><rp>）</rp></ruby>をー<br>　　　<ruby><rb>思</rb><rp>（</rp><rt>おも</rt><rp>）</rp><rb>ふ</rb><rp>（</rp><rt>ー</rt><rp>）</rp></ruby>ころーかなー</label>",
    },
    {
        no:  14,
        left: "キ",
        center: "ソ",
        right: "ニ",
        initial: "み",
        kimariji: "みち",
        kaminoku: "<label for='fuda'><font color='red'>みち</font>のくのーしのぶも<ruby><rb>ぢ</rb><rp>（</rp><rt>じ</rt><rp>）</rp></ruby>ずりー<br>　　　　　　<ruby><rb>誰</rb><rp>（</rp><rt>たれ</rt><rp>）</rp></ruby>ゆ<ruby><rb>ゑ</rb><rp>（</rp><rt>え</rt><rp>）</rp></ruby>ーにー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>乱</rb><rp>（</rp><rt>みだ</rt><rp>）</rp></ruby>れそめーにしー<br>　　　われならーなくにー</label>",
    },
    {
        no:  90,
        left: "ア",
        center: "タ",
        right: "ノ",
        initial: "み",
        kimariji: "みせ",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>見</rb><rp>（</rp><rt>み</rt><rp>）</rp></ruby>せ</font>ばやなー<ruby><rb>雄</rb><rp>（</rp><rt>お</rt><rp>）</rp><rb>島</rb><rp>（</rp><rt>じま</rt><rp>）</rp></ruby>のあまのー<br>　　　　　　<ruby><rb>袖</rb><rp>（</rp><rt>そで</rt><rp>）</rp></ruby>だにーもー</label>",
        shimonoku: "<label for='fuda'>ぬれにぞーぬれしー<br>　　　<ruby><rb>色</rb><rp>（</rp><rt>いろ</rt><rp>）</rp><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>か<ruby><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ーらずー</label>",
    },
    {
        no:  94,
        left: "カ",
        center: "チ",
        right: "ヒ",
        initial: "み",
        kimariji: "みよ",
        kaminoku: "<label for='fuda'><font color='red'>みよ</font>し<ruby><rb>野</rb><rp>（</rp><rt>の</rt><rp>）</rp></ruby>のー<ruby><rb>山</rb><rp>（</rp><rt>やま</rt><rp>）</rp></ruby>の<ruby><rb>秋</rb><rp>（</rp><rt>あき</rt><rp>）</rp><rb>風</rb><rp>（</rp><rt>かぜ</rt><rp>）</rp></ruby>ー<br>　　　　　　さ<ruby><rb>夜</rb><rp>（</rp><rt>よ</rt><rp>）</rp></ruby>ふけーてー</label>",
        shimonoku: "<label for='fuda'>ふるさとー<ruby><rb>寒</rb><rp>（</rp><rt>さむ</rt><rp>）</rp></ruby>くー<br>　　　<ruby><rb>衣</rb><rp>（</rp><rt>ころも</rt><rp>）</rp></ruby>うつーなりー</label>",
    },
    {
        no:  49,
        left: "コ",
        center: "ツ",
        right: "ネ",
        initial: "み",
        kimariji: "みかき",
        kaminoku: "<label for='fuda'><font color='red'>みかき</font>もりー<ruby><rb>衛</rb><rp>（</rp><rt>え</rt><rp>）</rp><rb>士</rb><rp>（</rp><rt>じ</rt><rp>）</rp></ruby>のたく<ruby><rb>火</rb><rp>（</rp><rt>ひ</rt><rp>）</rp></ruby>のー<br>　　　　　　<ruby><rb>夜</rb><rp>（</rp><rt>よる</rt><rp>）</rp><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ーもえー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>昼</rb><rp>（</rp><rt>ひる</rt><rp>）</rp><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ー<ruby><rb>消</rb><rp>（</rp><rt>き</rt><rp>）</rp></ruby>えつつー<br>　　　<ruby><rb>物</rb><rp>（</rp><rt>もの</rt><rp>）</rp></ruby>をこそー<ruby><rb>思</rb><rp>（</rp><rt>おも</rt><rp>）</rp><rb>へ</rb><rp>（</rp><rt>え</rt><rp>）</rp></ruby>ー</label>",
    },
    {
        no:  27,
        left: "イ",
        center: "セ",
        right: "ヘ",
        initial: "み",
        kimariji: "みかの",
        kaminoku: "<label for='fuda'><font color='red'>みかの</font><ruby><rb>原</rb><rp>（</rp><rt>はら</rt><rp>）</rp></ruby>ーわきて<ruby><rb>流</rb><rp>（</rp><rt>なが</rt><rp>）</rp></ruby>るるー<br>　　　　　　い<ruby><rb>づ</rb><rp>（</rp><rt>ず</rt><rp>）</rp></ruby>みー<ruby><rb>川</rb><rp>（</rp><rt>がわ</rt><rp>）</rp></ruby>ー</label>",
        shimonoku: "<label for='fuda'>いつ<ruby><rb>見</rb><rp>（</rp><rt>み</rt><rp>）</rp></ruby>きーとてかー<br>　　　<ruby><rb>恋</rb><rp>（</rp><rt>こい</rt><rp>）</rp></ruby>しかるーら<ruby><rb>む</rb><rp>（</rp><rt>ん</rt><rp>）</rp></ruby>ー</label>",
    },
    {
        no:  73,
        left: "キ",
        center: "チ",
        right: "フ",
        initial: "た",
        kimariji: "たか",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>高</rb><rp>（</rp><rt>たか</rt><rp>）</rp></ruby></font><ruby><rb>砂</rb><rp>（</rp><rt>さご</rt><rp>）</rp></ruby>のー<ruby><rb>尾上</rb><rp>（</rp><rt>おのえ</rt><rp>）</rp></ruby>の<ruby><rb>桜</rb><rp>（</rp><rt>さくら</rt><rp>）</rp></ruby>ー<br>　　　　　　<ruby><rb>咲</rb><rp>（</rp><rt>さ</rt><rp>）</rp></ruby>きにーけりー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>外</rb><rp>（</rp><rt>と</rt><rp>）</rp><rb>山</rb><rp>（</rp><rt>やま</rt><rp>）</rp></ruby>のー<ruby><rb>霞</rb><rp>（</rp><rt>かすみ</rt><rp>）</rp></ruby>ー<br>　　たたずもあらーな<ruby><rb>む</rb><rp>（</rp><rt>ん</rt><rp>）</rp></ruby>ー</label>",
    },
    {
        no:  16,
        left: "ケ",
        center: "タ",
        right: "ヒ",
        initial: "た",
        kimariji: "たち",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>立</rb><rp>（</rp><rt>た</rt><rp>）</rp></ruby>ち</font><ruby><rb>別</rb><rp>（</rp><rt>わか</rt><rp>）</rp></ruby>れーいなばの<ruby><rb>山</rb><rp>（</rp><rt>やま</rt><rp>）</rp></ruby>のー<br>　　　　　　<ruby><rb>峰</rb><rp>（</rp><rt>みね</rt><rp>）</rp></ruby>に<ruby><rb>生</rb><rp>（</rp><rt>お</rt><rp>）</rp><rb>ふ</rb><rp>（</rp><rt>(う)</rt><rp>）</rp></ruby>ーるー</label>",
        shimonoku: "<label for='fuda'>まつとしー<ruby><rb>聞</rb><rp>（</rp><rt>き</rt><rp>）</rp></ruby>かばー<br>　　　いま<ruby><rb>帰</rb><rp>（</rp><rt>かえ</rt><rp>）</rp></ruby>りーこ<ruby><rb>む</rb><rp>（</rp><rt>ん</rt><rp>）</rp></ruby>ー</label>",
    },
    {
        no:   4,
        left: "ウ",
        center: "シ",
        right: "ヌ",
        initial: "た",
        kimariji: "たご",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>田</rb><rp>（</rp><rt>た</rt><rp>）</rp><rb>子</rb><rp>（</rp><rt>ご</rt><rp>）</rp></ruby></font>の<ruby><rb>浦</rb><rp>（</rp><rt>うら</rt><rp>）</rp></ruby>にーうち<ruby><rb>出</rb><rp>（</rp><rt>い</rt><rp>）</rp></ruby>でて<ruby><rb>見</rb><rp>（</rp><rt>み</rt><rp>）</rp></ruby>ればー<br>　　　　　　<ruby><rb>白</rb><rp>（</rp><rt>しろ</rt><rp>）</rp><rb>妙</rb><rp>（</rp><rt>たえ</rt><rp>）</rp></ruby>ーのー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>富</rb><rp>（</rp><rt>ふ</rt><rp>）</rp><rb>士</rb><rp>（</rp><rt>じ</rt><rp>）</rp></ruby>のー<ruby><rb>高嶺</rb><rp>（</rp><rt>たかね</rt><rp>）</rp></ruby>にー<br>　　　<ruby><rb>雪</rb><rp>（</rp><rt>ゆき</rt><rp>）</rp><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ふりーつつー<br></label>",
    },
    {
        no:  89,
        left: "エ",
        center: "サ",
        right: "ナ",
        initial: "た",
        kimariji: "たま",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>玉</rb><rp>（</rp><rt>たま</rt><rp>）</rp></ruby></font>のをよーたえなばたえねー<br>　　　　　　ながら<ruby><rb>へ</rb><rp>（</rp><rt>え</rt><rp>）</rp></ruby>ーばー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>忍</rb><rp>（</rp><rt>しの</rt><rp>）</rp></ruby>ぶるーことのー<br>　　　<ruby><rb>弱</rb><rp>（</rp><rt>よわ</rt><rp>）</rp></ruby>りもぞーするー</label>",
    },
    {
        no:  55,
        left: "ア",
        center: "ス",
        right: "ホ",
        initial: "た",
        kimariji: "たき",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>滝</rb><rp>（</rp><rt>たき</rt><rp>）</rp></ruby></font>の<ruby><rb>音</rb><rp>（</rp><rt>おと</rt><rp>）</rp><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ーたえて<ruby><rb>久</rb><rp>（</rp><rt>ひさ</rt><rp>）</rp></ruby>しくー<br>　　　　　　なりぬれーどー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>名</rb><rp>（</rp><rt>な</rt><rp>）</rp></ruby>こそー<ruby><rb>流</rb><rp>（</rp><rt>なが</rt><rp>）</rp></ruby>れてー<br>　　　な<ruby><rb>ほ</rb><rp>（</rp><rt>お</rt><rp>）</rp><rb>聞</rb><rp>（</rp><rt>き</rt><rp>）</rp></ruby>こえーけれー</label>",
    },
    {
        no:  34,
        left: "ク",
        center: "ソ",
        right: "ヘ",
        initial: "た",
        kimariji: "たれ",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>誰</rb><rp>（</rp><rt>たれ</rt><rp>）</rp></ruby></font>をかもー<ruby><rb>知</rb><rp>（</rp><rt>し</rt><rp>）</rp></ruby>る<ruby><rb>人</rb><rp>（</rp><rt>ひと</rt><rp>）</rp></ruby>にせ<ruby><rb>む</rb><rp>（</rp><rt>ん</rt><rp>）</rp></ruby>ー<br>　　　　　　<ruby><rb>高</rb><rp>（</rp><rt>たか</rt><rp>）</rp><rb>砂</rb><rp>（</rp><rt>さご</rt><rp>）</rp></ruby>ーのー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>松</rb><rp>（</rp><rt>まつ</rt><rp>）</rp></ruby>もー<ruby><rb>昔</rb><rp>（</rp><rt>むかし</rt><rp>）</rp></ruby>のー<br>　　　<ruby><rb>友</rb><rp>（</rp><rt>とも</rt><rp>）</rp></ruby>ならーなくにー</label>",
    },
    {
        no:  97,
        left: "ク",
        center: "タ",
        right: "ヘ",
        initial: "こ",
        kimariji: "こぬ",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>来</rb><rp>（</rp><rt>こ</rt><rp>）</rp></ruby>ぬ</font><ruby><rb>人</rb><rp>（</rp><rt>ひと</rt><rp>）</rp></ruby>をーまつほの<ruby><rb>浦</rb><rp>（</rp><rt>うら</rt><rp>）</rp></ruby>のー<br>　　　　　　<ruby><rb>夕</rb><rp>（</rp><rt>ゆー</rt><rp>）</rp></ruby>なぎーにー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>焼</rb><rp>（</rp><rt>や</rt><rp>）</rp></ruby>くやーもし<ruby><rb>ほ</rb><rp>（</rp><rt>お</rt><rp>）</rp></ruby>のー<br>　　　<ruby><rb>身</rb><rp>（</rp><rt>み</rt><rp>）</rp></ruby>もこがれーつつー</label>",
    },
    {
        no:  24,
        left: "エ",
        center: "ト",
        right: "フ",
        initial: "こ",
        kimariji: "この",
        kaminoku: "<label for='fuda'><font color='red'>この</font>たび<ruby><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ーぬさもとりあ<ruby><rb>へ</rb><rp>（</rp><rt>え</rt><rp>）</rp></ruby>ずー<br>　　　　　　<ruby><rb>手向</rb><rp>（</rp><rt>たむけ</rt><rp>）</rp></ruby>ー<ruby><rb>山</rb><rp>（</rp><rt>やま</rt><rp>）</rp></ruby>ー</label>",
        shimonoku: "<label for='fuda'>もみ<ruby><rb>ぢ</rb><rp>（</rp><rt>じ</rt><rp>）</rp></ruby>のーにしきー<br>　　　<ruby><rb>神</rb><rp>（</rp><rt>かみ</rt><rp>）</rp></ruby>のまにーまにー</label>",
    },
    {
        no:  10,
        left: "オ",
        center: "シ",
        right: "ハ",
        initial: "こ",
        kimariji: "これ",
        kaminoku: "<label for='fuda'><font color='red'>これ</font>やこのー<ruby><rb>行</rb><rp>（</rp><rt>ゆ</rt><rp>）</rp></ruby>くもー<ruby><rb>帰</rb><rp>（</rp><rt>かえ</rt><rp>）</rp></ruby>るもー<br>　　　　　　<ruby><rb>別</rb><rp>（</rp><rt>わか</rt><rp>）</rp></ruby>れてーはー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>知</rb><rp>（</rp><rt>し</rt><rp>）</rp></ruby>るもー<ruby><rb>知</rb><rp>（</rp><rt>し</rt><rp>）</rp></ruby>らぬもー<br>　　　<ruby><rb>逢</rb><rp>（</rp><rt>おー</rt><rp>）</rp><rb>坂</rb><rp>（</rp><rt>さか</rt><rp>）</rp></ruby>のー<ruby><rb>関</rb><rp>（</rp><rt>せき</rt><rp>）</rp></ruby>ー</label>",
    },
    {
        no:  41,
        left: "ケ",
        center: "ツ",
        right: "ノ",
        initial: "こ",
        kimariji: "こい",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>恋</rb><rp>（</rp><rt>こい</rt><rp>）</rp></ruby></font>す<ruby><rb>てふ</rb><rp>（</rp><rt>ちょー</rt><rp>）</rp></ruby>ーわが<ruby><rb>名</rb><rp>（</rp><rt>な</rt><rp>）</rp><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>まだきー<br>　　　　　　<ruby><rb>立</rb><rp>（</rp><rt>た</rt><rp>）</rp></ruby>ちにーけりー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>人</rb><rp>（</rp><rt>ひと</rt><rp>）</rp></ruby>ーしれずこそー<br>　　　<ruby><rb>思</rb><rp>（</rp><rt>おも</rt><rp>）</rp><rb>ひ</rb><rp>（</rp><rt>い</rt><rp>）</rp></ruby>そめーしかー</label>",
    },
    {
        no:  29,
        left: "イ",
        center: "チ",
        right: "ニ",
        initial: "こ",
        kimariji: "こころあ",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>心</rb><rp>（</rp><rt>こころ</rt><rp>）</rp></ruby>あ</font>てにー<ruby><rb>折</rb><rp>（</rp><rt>お</rt><rp>）</rp></ruby>らばや<ruby><rb>折</rb><rp>（</rp><rt>お</rt><rp>）</rp></ruby>ら<ruby><rb>む</rb><rp>（</rp><rt>ん</rt><rp>）</rp></ruby>ー<br>　　　　　　<ruby><rb>初</rb><rp>（</rp><rt>はつ</rt><rp>）</rp><rb>霜</rb><rp>（</rp><rt>しも</rt><rp>）</rp></ruby>ーのー</label>",
        shimonoku: "<label for='fuda'>おきーまど<ruby><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>せるー<br>　　　<ruby><rb>白</rb><rp>（</rp><rt>しら</rt><rp>）</rp><rb>菊</rb><rp>（</rp><rt>ぎく</rt><rp>）</rp></ruby>のー<ruby><rb>花</rb><rp>（</rp><rt>はな</rt><rp>）</rp></ruby>ー</label>",
    },
    {
        no:  68,
        left: "コ",
        center: "セ",
        right: "ネ",
        initial: "こ",
        kimariji: "こころに",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>心</rb><rp>（</rp><rt>こころ</rt><rp>）</rp></ruby>に</font>もーあらでうき<ruby><rb>世</rb><rp>（</rp><rt>よ</rt><rp>）</rp></ruby>にー<br>　　　　　　ながら<ruby><rb>へ</rb><rp>（</rp><rt>え</rt><rp>）</rp></ruby>ーばー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>恋</rb><rp>（</rp><rt>こい</rt><rp>）</rp></ruby>しかるーべきー<br>　　　<ruby><rb>夜</rb><rp>（</rp><rt>よ</rt><rp>）</rp><rb>半</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>の<ruby><rb>月</rb><rp>（</rp><rt>つき</rt><rp>）</rp></ruby>ーかなー</label>",
    },
    {
        no:   5,
        left: "ア",
        center: "チ",
        right: "ナ",
        initial: "お",
        kimariji: "おく",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>奥</rb><rp>（</rp><rt>おく</rt><rp>）</rp></ruby></font><ruby><rb>山</rb><rp>（</rp><rt>やま</rt><rp>）</rp></ruby>にーもみ<ruby><rb>ぢ</rb><rp>（</rp><rt>じ</rt><rp>）</rp></ruby>ふみわけー<br>　　　　　　<ruby><rb>鳴</rb><rp>（</rp><rt>な</rt><rp>）</rp></ruby>く<ruby><rb>鹿</rb><rp>（</rp><rt>しか</rt><rp>）</rp></ruby>ーのー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>声</rb><rp>（</rp><rt>こえ</rt><rp>）</rp></ruby>ー<ruby><rb>聞</rb><rp>（</rp><rt>き</rt><rp>）</rp></ruby>くときぞー<br>　　　<ruby><rb>秋</rb><rp>（</rp><rt>あき</rt><rp>）</rp></ruby>は<ruby><rb>悲</rb><rp>（</rp><rt>かな</rt><rp>）</rp></ruby>ーしきー</label>",
    },
    {
        no:  26,
        left: "キ",
        center: "テ",
        right: "ニ",
        initial: "お",
        kimariji: "おぐ",
        kaminoku: "<label for='fuda'><font color='red'>おぐ</font>ら<ruby><rb>山</rb><rp>（</rp><rt>やま</rt><rp>）</rp></ruby>ー<ruby><rb>峰</rb><rp>（</rp><rt>みね</rt><rp>）</rp></ruby>のもみ<ruby><rb>ぢ</rb><rp>（</rp><rt>じ</rt><rp>）</rp><rb>葉</rb><rp>（</rp><rt>ば</rt><rp>）</rp></ruby>ー<br>　　　　　　<ruby><rb>心</rb><rp>（</rp><rt>こころ</rt><rp>）</rp></ruby>あらーばー</label>",
        shimonoku: "<label for='fuda'>いまーひとたびのー<br>　　　みゆき<ruby><rb>待</rb><rp>（</rp><rt>ま</rt><rp>）</rp></ruby>たーな<ruby><rb>む</rb><rp>（</rp><rt>ん</rt><rp>）</rp></ruby>ー</label>",
    },
    {
        no:  72,
        left: "カ",
        center: "ツ",
        right: "ホ",
        initial: "お",
        kimariji: "おと",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>音</rb><rp>（</rp><rt>おと</rt><rp>）</rp></ruby></font>にきくーたかしの<ruby><rb>浜</rb><rp>（</rp><rt>はま</rt><rp>）</rp></ruby>のー<br>　　　　　　あだ<ruby><rb>波</rb><rp>（</rp><rt>なみ</rt><rp>）</rp></ruby>ーはー</label>",
        shimonoku: "<label for='fuda'>かけじやー<ruby><rb>袖</rb><rp>（</rp><rt>そで</rt><rp>）</rp></ruby>のー<br>　　　ぬれもこそーすれー</label>",
    },
    {
        no:  82,
        left: "ウ",
        center: "ソ",
        right: "ヌ",
        initial: "お",
        kimariji: "おも",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>思</rb><rp>（</rp><rt>おも</rt><rp>）</rp></ruby></font><ruby><rb>ひ</rb><rp>（</rp><rt>い</rt><rp>）</rp></ruby>わびーさても<ruby><rb>命</rb><rp>（</rp><rt>いのち</rt><rp>）</rp><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ー<br>　　　　　　あるものーをー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>憂</rb><rp>（</rp><rt>う</rt><rp>）</rp></ruby>きにーた<ruby><rb>へ</rb><rp>（</rp><rt>え</rt><rp>）</rp></ruby>ぬ<ruby><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ー<br>　　　<ruby><rb>涙</rb><rp>（</rp><rt>なみだ</rt><rp>）</rp></ruby>なりーけりー</label>",
    },
    {
        no:  60,
        left: "オ",
        center: "ト",
        right: "ノ",
        initial: "お",
        kimariji: "おおえ",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>大江</rb><rp>（</rp><rt>お(お)え</rt><rp>）</rp></ruby></font><ruby><rb>山</rb><rp>（</rp><rt>やま</rt><rp>）</rp></ruby>ーいく<ruby><rb>野</rb><rp>（</rp><rt>の</rt><rp>）</rp></ruby>の<ruby><rb>道</rb><rp>（</rp><rt>みち</rt><rp>）</rp></ruby>のー<br>　　　　　　<ruby><rb>遠</rb><rp>（</rp><rt>とー</rt><rp>）</rp></ruby>けれーばー</label>",
        shimonoku: "<label for='fuda'>まだーふみも<ruby><rb>見</rb><rp>（</rp><rt>み</rt><rp>）</rp></ruby>ずー<br>　　　<ruby><rb>天</rb><rp>（</rp><rt>あま</rt><rp>）</rp></ruby>の<ruby><rb>橋</rb><rp>（</rp><rt>はし</rt><rp>）</rp></ruby>ー<ruby><rb>立</rb><rp>（</rp><rt>だて</rt><rp>）</rp></ruby>ー</label>",
    },
    {
        no:  95,
        left: "コ",
        center: "シ",
        right: "ヘ",
        initial: "お",
        kimariji: "おおけ",
        kaminoku: "<label for='fuda'><font color='red'>お<ruby><rb>ほ</rb><rp>（</rp><rt>(お)</rt><rp>）</rp></ruby>け</font>なくーうき<ruby><rb>世</rb><rp>（</rp><rt>よ</rt><rp>）</rp></ruby>の<ruby><rb>民</rb><rp>（</rp><rt>たみ</rt><rp>）</rp></ruby>にー<br>　　　　　　お<ruby><rb>ほ</rb><rp>（</rp><rt>(お)</rt><rp>）</rp><rb>ふ</rb><rp>（</rp><rt>ー</rt><rp>）</rp></ruby>ーかなー</label>",
        shimonoku: "<label for='fuda'>わがー<ruby><rb>立</rb><rp>（</rp><rt>た</rt><rp>）</rp></ruby>つ<ruby><rb>杣</rb><rp>（</rp><rt>そま</rt><rp>）</rp></ruby>にー<br>　　　<ruby><rb>墨</rb><rp>（</rp><rt>すみ</rt><rp>）</rp><rb>染</rb><rp>（</rp><rt>ぞめ</rt><rp>）</rp></ruby>のー<ruby><rb>袖</rb><rp>（</rp><rt>そで</rt><rp>）</rp></ruby>ー</label>",
    },
    {
        no:  44,
        left: "イ",
        center: "サ",
        right: "ヒ",
        initial: "お",
        kimariji: "おおこ",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>逢</rb><rp>（</rp><rt>お</rt><rp>）</rp><rb>ふ</rb><rp>（</rp><rt>(お)</rt><rp>）</rp></ruby>こ</font>とのーたえてしなくばー<br>　　　　　　なかなかーにー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>人</rb><rp>（</rp><rt>ひと</rt><rp>）</rp></ruby>をもー<ruby><rb>身</rb><rp>（</rp><rt>み</rt><rp>）</rp></ruby>をもー<br>　　　<ruby><rb>恨</rb><rp>（</rp><rt>うら</rt><rp>）</rp></ruby>みざらーましー</label>",
    },
    {
        no:  20,
        left: "コ",
        center: "ソ",
        right: "ナ",
        initial: "わ",
        kimariji: "わび",
        kaminoku: "<label for='fuda'><font color='red'>わび</font>ぬればーいま<ruby><rb>は</rb><rp>（</rp><rt>は</rt><rp>）</rp></ruby>たおなじー<br>　　　　　　<ruby><rb>難波</rb><rp>（</rp><rt>なにわ</rt><rp>）</rp></ruby>ーなるー</label>",
        shimonoku: "<label for='fuda'>みをーつくしてもー<br>　　　あ<ruby><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp><rb>む</rb><rp>（</rp><rt>ん</rt><rp>）</rp></ruby>とぞー<ruby><rb>思</rb><rp>（</rp><rt>おも</rt><rp>）</rp><rb>ふ</rb><rp>（</rp><rt>(お)</rt><rp>）</rp></ruby>ー</label>",
    },
    {
        no:   8,
        left: "エ",
        center: "シ",
        right: "ネ",
        initial: "わ",
        kimariji: "わがい",
        kaminoku: "<label for='fuda'><font color='red'>わがい</font><ruby><rb>ほ</rb><rp>（</rp><rt>お</rt><rp>）</rp><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ー<ruby><rb>都</rb><rp>（</rp><rt>みやこ</rt><rp>）</rp></ruby>のたつみー<br>　　　　　　しかぞーすむー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>世</rb><rp>（</rp><rt>よ</rt><rp>）</rp></ruby>をーう<ruby><rb>ぢ</rb><rp>（</rp><rt>じ</rt><rp>）</rp><rb>山</rb><rp>（</rp><rt>やま</rt><rp>）</rp></ruby>とー<br>　　　<ruby><rb>人</rb><rp>（</rp><rt>ひと</rt><rp>）</rp><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp><rb>い</rb><rp>（</rp><rt>ゆ</rt><rp>）</rp><rb>ふ</rb><rp>（</rp><rt>ー</rt><rp>）</rp></ruby>ーなりー</label>",
    },
    {
        no:  92,
        left: "カ",
        center: "ツ",
        right: "フ",
        initial: "わ",
        kimariji: "わがそ",
        kaminoku: "<label for='fuda'><font color='red'>わがそ</font>で<ruby><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ー<ruby><rb>潮</rb><rp>（</rp><rt>しお</rt><rp>）</rp><rb>干</rb><rp>（</rp><rt>ひ</rt><rp>）</rp></ruby>にみえぬー<br>　　　　　　<ruby><rb>沖</rb><rp>（</rp><rt>おき</rt><rp>）</rp></ruby>の<ruby><rb>石</rb><rp>（</rp><rt>いし</rt><rp>）</rp></ruby>ーのー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>人</rb><rp>（</rp><rt>ひと</rt><rp>）</rp></ruby>こそーしらねー<br>　　　かわくまもーなしー</label>",
    },
    {
        no:  54,
        left: "ケ",
        center: "ソ",
        right: "ハ",
        initial: "わ",
        kimariji: "わすれ",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>忘</rb><rp>（</rp><rt>わす</rt><rp>）</rp></ruby>れ</font>じのーゆくす<ruby><rb>ゑ</rb><rp>（</rp><rt>え</rt><rp>）</rp></ruby>まで<ruby><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ー<br>　　　　　　かたけれーばー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>けふ</rb><rp>（</rp><rt>きょー</rt><rp>）</rp></ruby>をーかぎりのー<br>　　　いのちとーもがなー</label>",
    },
    {
        no:  38,
        left: "キ",
        center: "ス",
        right: "ヌ",
        initial: "わ",
        kimariji: "わすら",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>忘</rb><rp>（</rp><rt>わす</rt><rp>）</rp></ruby>ら</font>るるー<ruby><rb>身</rb><rp>（</rp><rt>み</rt><rp>）</rp></ruby>をば<ruby><rb>思</rb><rp>（</rp><rt>おも</rt><rp>）</rp><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ずー<br>　　　　　　ちか<ruby><rb>ひ</rb><rp>（</rp><rt>い</rt><rp>）</rp></ruby>てーしー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>人</rb><rp>（</rp><rt>ひと</rt><rp>）</rp></ruby>のー<ruby><rb>命</rb><rp>（</rp><rt>いのち</rt><rp>）</rp></ruby>のー<br>　　<ruby><rb>惜</rb><rp>（</rp><rt>お</rt><rp>）</rp></ruby>しくもあるーかなー</label>",
    },
    {
        no:  11,
        left: "オ",
        center: "テ",
        right: "ノ",
        initial: "わ",
        kimariji: "わた・や",
        kaminoku: "<label for='fuda'><font color='red'>わたの<ruby><rb>原</rb><rp>（</rp><rt>はら</rt><rp>）</rp><rb>八</rb><rp>（</rp><rt>や</rt><rp>）</rp></ruby></font><ruby><rb>十</rb><rp>（</rp><rt>そ</rt><rp>）</rp><rb>島</rb><rp>（</rp><rt>しま</rt><rp>）</rp></ruby>ーかけてー<br>　　　　　　<ruby><rb>漕</rb><rp>（</rp><rt>こ</rt><rp>）</rp></ruby>ぎ<ruby><rb>出</rb><rp>（</rp><rt>い</rt><rp>）</rp></ruby>でぬーとー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>人</rb><rp>（</rp><rt>ひと</rt><rp>）</rp></ruby>に<ruby><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ー<ruby><rb>告</rb><rp>（</rp><rt>つ</rt><rp>）</rp></ruby>げよー<br>　　　あまのつりー<ruby><rb>舟</rb><rp>（</rp><rt>ぶね</rt><rp>）</rp></ruby>ー</label>",
    },
    {
        no:  76,
        left: "ク",
        center: "ト",
        right: "ニ",
        initial: "わ",
        kimariji: "わた・こ",
        kaminoku: "<label for='fuda'><font color='red'>わたの<ruby><rb>原</rb><rp>（</rp><rt>はら</rt><rp>）</rp><rb>漕</rb><rp>（</rp><rt>こ</rt><rp>）</rp></ruby></font>ぎ<ruby><rb>出</rb><rp>（</rp><rt>い</rt><rp>）</rp></ruby>でてー<ruby><rb>見</rb><rp>（</rp><rt>み</rt><rp>）</rp></ruby>ればー<br>　　　　　　<ruby><rb>久</rb><rp>（</rp><rt>ひさ</rt><rp>）</rp><rb>方</rb><rp>（</rp><rt>かた</rt><rp>）</rp></ruby>ーのー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>雲</rb><rp>（</rp><rt>くも</rt><rp>）</rp><rb>ゐ</rb><rp>（</rp><rt>い</rt><rp>）</rp></ruby>にーま<ruby><rb>が</rb><rp>（</rp><rt>ご</rt><rp>）</rp><rb>ふ</rb><rp>（</rp><rt>ー</rt><rp>）</rp></ruby>ー<br>　　　　　　<ruby><rb>沖</rb><rp>（</rp><rt>おき</rt><rp>）</rp></ruby>つ<ruby><rb>白</rb><rp>（</rp><rt>しら</rt><rp>）</rp></ruby>ー<ruby><rb>波</rb><rp>（</rp><rt>なみ</rt><rp>）</rp></ruby>ー</label>",
    },
    {
        no:  36,
        left: "カ",
        center: "チ",
        right: "ノ",
        initial: "な",
        kimariji: "なつ",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>夏</rb><rp>（</rp><rt>なつ</rt><rp>）</rp></ruby></font>の<ruby><rb>夜</rb><rp>（</rp><rt>よ</rt><rp>）</rp><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ーまだ<ruby><rb>宵</rb><rp>（</rp><rt>よい</rt><rp>）</rp></ruby>ながらー<br>　　　　　　<ruby><rb>明</rb><rp>（</rp><rt>あ</rt><rp>）</rp></ruby>けぬるーをー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>雲</rb><rp>（</rp><rt>くも</rt><rp>）</rp></ruby>のーい<ruby><rb>づ</rb><rp>（</rp><rt>ず</rt><rp>）</rp></ruby>こにー<br>　　　<ruby><rb>月</rb><rp>（</rp><rt>つき</rt><rp>）</rp><rb>宿</rb><rp>（</rp><rt>やど</rt><rp>）</rp></ruby>るーら<ruby><rb>む</rb><rp>（</rp><rt>ん</rt><rp>）</rp></ruby>ー</label>",
    },
    {
        no:  25,
        left: "ウ",
        center: "タ",
        right: "ハ",
        initial: "な",
        kimariji: "なにし",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>名</rb><rp>（</rp><rt>な</rt><rp>）</rp></ruby>にし</font>お<ruby><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ばー<ruby><rb>逢</rb><rp>（</rp><rt>おー</rt><rp>）</rp><rb>坂</rb><rp>（</rp><rt>さか</rt><rp>）</rp><rb>山</rb><rp>（</rp><rt>やま</rt><rp>）</rp></ruby>のー<br>　　　　　　さねか<ruby><rb>づ</rb><rp>（</rp><rt>ず</rt><rp>）</rp></ruby>ーらー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>人</rb><rp>（</rp><rt>ひと</rt><rp>）</rp></ruby>にー<ruby><rb>知</rb><rp>（</rp><rt>し</rt><rp>）</rp></ruby>られでー<br>　　　くるよしーもがなー</label>",
    },
    {
        no:  19,
        left: "エ",
        center: "テ",
        right: "ヘ",
        initial: "な",
        kimariji: "なにわが",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>難波</rb><rp>（</rp><rt>なにわ</rt><rp>）</rp></ruby>が</font>たー<ruby><rb>短</rb><rp>（</rp><rt>みじか</rt><rp>）</rp></ruby>き<ruby><rb>芦</rb><rp>（</rp><rt>あし</rt><rp>）</rp></ruby>のー<br>　　　　　　ふしの<ruby><rb>間</rb><rp>（</rp><rt>ま</rt><rp>）</rp></ruby>ーもー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>逢</rb><rp>（</rp><rt>あ</rt><rp>）</rp><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>でーこの<ruby><rb>世</rb><rp>（</rp><rt>よ</rt><rp>）</rp></ruby>をー<br>　　　<ruby><rb>過</rb><rp>（</rp><rt>す</rt><rp>）</rp></ruby>ぐしてよーとやー</label>",
    },
    {
        no:  88,
        left: "ア",
        center: "セ",
        right: "フ",
        initial: "な",
        kimariji: "なにわえ",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>難波江</rb><rp>（</rp><rt>なにわえ</rt><rp>）</rp></ruby></font>のー<ruby><rb>芦</rb><rp>（</rp><rt>あし</rt><rp>）</rp></ruby>のかりねのー<br>　　　ひとよーゆ<ruby><rb>ゑ</rb><rp>（</rp><rt>え</rt><rp>）</rp></ruby>ー</label>",
        shimonoku: "<label for='fuda'>みをーつくしてやー<br>　　　<ruby><rb>恋</rb><rp>（</rp><rt>こ</rt><rp>）</rp><rb>ひ</rb><rp>（</rp><rt>い</rt><rp>）</rp></ruby>わたるーべきー</label>",
    },
    {
        no:  84,
        left: "オ",
        center: "サ",
        right: "ネ",
        initial: "な",
        kimariji: "ながら",
        kaminoku: "<label for='fuda'><font color='red'>ながら</font><ruby><rb>へ</rb><rp>（</rp><rt>え</rt><rp>）</rp></ruby>ばーまたこのごろやー<br>　　　　　　しのばれー<ruby><rb>む</rb><rp>（</rp><rt>ん</rt><rp>）</rp></ruby>ー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>憂</rb><rp>（</rp><rt>う</rt><rp>）</rp></ruby>しとー<ruby><rb>見</rb><rp>（</rp><rt>み</rt><rp>）</rp></ruby>し<ruby><rb>世</rb><rp>（</rp><rt>よ</rt><rp>）</rp></ruby>ぞー<br>　　　<ruby><rb>今</rb><rp>（</rp><rt>いま</rt><rp>）</rp><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp><rb>恋</rb><rp>（</rp><rt>こい</rt><rp>）</rp></ruby>ーしきー</label>",
    },
    {
        no:  80,
        left: "ケ",
        center: "ツ",
        right: "ナ",
        initial: "な",
        kimariji: "ながか",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>長</rb><rp>（</rp><rt>なが</rt><rp>）</rp></ruby>か</font>ら<ruby><rb>む</rb><rp>（</rp><rt>ん</rt><rp>）</rp></ruby>ー<ruby><rb>心</rb><rp>（</rp><rt>こころ</rt><rp>）</rp></ruby>もしらずー<br>　　　　　　<ruby><rb>黒</rb><rp>（</rp><rt>くろ</rt><rp>）</rp><rb>髪</rb><rp>（</rp><rt>かみ</rt><rp>）</rp></ruby>ーのー</label>",
        shimonoku: "<label for='fuda'>みだれてー<ruby><rb>今</rb><rp>（</rp><rt>け</rt><rp>）</rp><rb>朝</rb><rp>（</rp><rt>さ</rt><rp>）</rp><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ー<br>　　　<ruby><rb>物</rb><rp>（</rp><rt>もの</rt><rp>）</rp></ruby>をこそー<ruby><rb>思</rb><rp>（</rp><rt>おも</rt><rp>）</rp><rb>へ</rb><rp>（</rp><rt>え</rt><rp>）</rp></ruby>ー</label>",
    },
    {
        no:  53,
        left: "キ",
        center: "ソ",
        right: "ホ",
        initial: "な",
        kimariji: "なげき",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>嘆</rb><rp>（</rp><rt>なげ</rt><rp>）</rp></ruby>き</font>つつーひとりぬる<ruby><rb>夜</rb><rp>（</rp><rt>よ</rt><rp>）</rp></ruby>のー<br>　　　　　　<ruby><rb>明</rb><rp>（</rp><rt>あ</rt><rp>）</rp></ruby>くるまー<ruby><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ー</label>",
        shimonoku: "<label for='fuda'>いかにー<ruby><rb>久</rb><rp>（</rp><rt>ひさ</rt><rp>）</rp></ruby>しきー<br>　　　ものとか<ruby><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ーしるー</label>",
    },
    {
        no:  86,
        left: "ク",
        center: "ス",
        right: "ヒ",
        initial: "な",
        kimariji: "なげけ",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>嘆</rb><rp>（</rp><rt>なげ</rt><rp>）</rp></ruby>け</font>とてー<ruby><rb>月</rb><rp>（</rp><rt>つき</rt><rp>）</rp></ruby>や<ruby><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp><rb>物</rb><rp>（</rp><rt>もの</rt><rp>）</rp></ruby>をー<br>　　　　　　<ruby><rb>思</rb><rp>（</rp><rt>おも</rt><rp>）</rp><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ーするー</label>",
        shimonoku: "<label for='fuda'>かこち<ruby><rb>顔</rb><rp>（</rp><rt>がお</rt><rp>）</rp></ruby>ーなるー<br>　　　わが<ruby><rb>涙</rb><rp>（</rp><rt>なみだ</rt><rp>）</rp></ruby>ーかなー</label>",
    },
    {
        no:  78,
        left: "イ",
        center: "セ",
        right: "ノ",
        initial: "あ",
        kimariji: "あわじ",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>淡</rb><rp>（</rp><rt>あわ</rt><rp>）</rp><rb>路</rb><rp>（</rp><rt>じ</rt><rp>）</rp></ruby></font><ruby><rb>島</rb><rp>（</rp><rt>しま</rt><rp>）</rp></ruby>ーかよ<ruby><rb>ふ</rb><rp>（</rp><rt>ー</rt><rp>）</rp><rb>千</rb><rp>（</rp><rt>ち</rt><rp>）</rp><rb>鳥</rb><rp>（</rp><rt>どり</rt><rp>）</rp></ruby>のー<br>　　　　　　<ruby><rb>鳴</rb><rp>（</rp><rt>な</rt><rp>）</rp></ruby>く<ruby><rb>声</rb><rp>（</rp><rt>こえ</rt><rp>）</rp></ruby>ーにー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>幾</rb><rp>（</rp><rt>いく</rt><rp>）</rp><rb>夜</rb><rp>（</rp><rt>よ</rt><rp>）</rp></ruby>ーねざめぬー<br>　　　<ruby><rb>須</rb><rp>（</rp><rt>す</rt><rp>）</rp><rb>磨</rb><rp>（</rp><rt>ま</rt><rp>）</rp></ruby>の<ruby><rb>関</rb><rp>（</rp><rt>せき</rt><rp>）</rp></ruby>ー<ruby><rb>守</rb><rp>（</rp><rt>もり</rt><rp>）</rp></ruby>ー</label>",
    },
    {
        no:  45,
        left: "ウ",
        center: "ソ",
        right: "ネ",
        initial: "あ",
        kimariji: "あわれ",
        kaminoku: "<label for='fuda'><font color='red'>あ<ruby><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>れ</font>ともー<ruby><rb>い</rb><rp>（</rp><rt>ゆ</rt><rp>）</rp><rb>ふ</rb><rp>（</rp><rt>ー</rt><rp>）</rp></ruby>べき<ruby><rb>人</rb><rp>（</rp><rt>ひと</rt><rp>）</rp><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ー<br>　　　　　　<ruby><rb>思</rb><rp>（</rp><rt>おも</rt><rp>）</rp><rb>ほ</rb><rp>（</rp><rt>(お)</rt><rp>）</rp></ruby>えーでー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>身</rb><rp>（</rp><rt>み</rt><rp>）</rp></ruby>のーいた<ruby><rb>づ</rb><rp>（</rp><rt>ず</rt><rp>）</rp></ruby>らにー<br>　　　なりぬべきーかなー</label>",
    },
    {
        no:  69,
        left: "ク",
        center: "タ",
        right: "フ",
        initial: "あ",
        kimariji: "あらし",
        kaminoku: "<label for='fuda'><font color='red'>あらし</font><ruby><rb>吹</rb><rp>（</rp><rt>ふ</rt><rp>）</rp></ruby>くー<ruby><rb>三</rb><rp>（</rp><rt>み</rt><rp>）</rp><rb>室</rb><rp>（</rp><rt>むろ</rt><rp>）</rp></ruby>の<ruby><rb>山</rb><rp>（</rp><rt>やま</rt><rp>）</rp></ruby>のー<br>　　　　　　もみ<ruby><rb>ぢ</rb><rp>（</rp><rt>じ</rt><rp>）</rp><rb>葉</rb><rp>（</rp><rt>ば</rt><rp>）</rp></ruby>ー<ruby><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>竜</rb><rp>（</rp><rt>たつ</rt><rp>）</rp><rb>田</rb><rp>（</rp><rt>た</rt><rp>）</rp></ruby>のー<ruby><rb>川</rb><rp>（</rp><rt>かわ</rt><rp>）</rp></ruby>のー<br>　　　<ruby><rb>錦</rb><rp>（</rp><rt>にしき</rt><rp>）</rp></ruby>なりーけりー</label>",
    },
    {
        no:  56,
        left: "エ",
        center: "チ",
        right: "ホ",
        initial: "あ",
        kimariji: "あらざ",
        kaminoku: "<label for='fuda'><font color='red'>あらざ</font>ら<ruby><rb>む</rb><rp>（</rp><rt>ん</rt><rp>）</rp></ruby>ーこの<ruby><rb>世</rb><rp>（</rp><rt>よ</rt><rp>）</rp></ruby>のほかのー<br>　　　　　　<ruby><rb>思</rb><rp>（</rp><rt>おも</rt><rp>）</rp><rb>ひ</rb><rp>（</rp><rt>い</rt><rp>）</rp><rb>出</rb><rp>（</rp><rt>で</rt><rp>）</rp></ruby>ーにー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>今</rb><rp>（</rp><rt>いま</rt><rp>）</rp></ruby>ーひとたびのー<br>　　　<ruby><rb>あ</rb><rp>（</rp><rt>お</rt><rp>）</rp><rb>ふ</rb><rp>（</rp><rt>ー</rt><rp>）</rp></ruby>ことーもがなー</label>",
    },
    {
        no:   1,
        left: "ア",
        center: "シ",
        right: "ヒ",
        initial: "あ",
        kimariji: "あきの",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>秋</rb><rp>（</rp><rt>あき</rt><rp>）</rp></ruby>の</font><ruby><rb>田</rb><rp>《</rp><rt>た</rt><rp>》</rp></ruby>のーかり<ruby><rb>ほ</rb><rp>《</rp><rt>お</rt><rp>》</rp></ruby>の<ruby><rb>庵</rb><rp>《</rp><rt>いお</rt><rp>》</rp></ruby>のー<br>　　　　　　<ruby><rb>苫</rb><rp>《</rp><rt>とま</rt><rp>》</rp></ruby>をあらーみー</label>",
        shimonoku: "<label for='fuda'>わがー<ruby><rb>衣</rb><rp>（</rp><rt>ころも</rt><rp>）</rp><rb>手</rb><rp>（</rp><rt>で</rt><rp>）</rp><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ー<br>　　　<ruby><rb>露</rb><rp>《</rp><rt>つゆ</rt><rp>》</rp></ruby>にぬれーつつー</label>",
    },
    {
        no:  79,
        left: "ウ",
        center: "ツ",
        right: "ヘ",
        initial: "あ",
        kimariji: "あきか",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>秋</rb><rp>（</rp><rt>あき</rt><rp>）</rp></ruby>か</font>ぜにーたなびく<ruby><rb>雲</rb><rp>（</rp><rt>くも</rt><rp>）</rp></ruby>のー<br>　　　　　　たえ<ruby><rb>間</rb><rp>（</rp><rt>ま</rt><rp>）</rp></ruby>ーよりー</label>",
        shimonoku: "<label for='fuda'>もれ<ruby><rb>出</rb><rp>（</rp><rt>い</rt><rp>）</rp><rb>づ</rb><rp>（</rp><rt>ず</rt><rp>）</rp></ruby>るー<ruby><rb>月</rb><rp>（</rp><rt>つき</rt><rp>）</rp></ruby>のー<br>　　　<ruby><rb>影</rb><rp>（</rp><rt>かげ</rt><rp>）</rp></ruby>のさやーけさー</label>",
    },
    {
        no:  12,
        left: "イ",
        center: "テ",
        right: "ヌ",
        initial: "あ",
        kimariji: "あまつ",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>天</rb><rp>（</rp><rt>あま</rt><rp>）</rp><rb>津</rb><rp>（</rp><rt>つ</rt><rp>）</rp></ruby></font><ruby><rb>風</rb><rp>（</rp><rt>かぜ</rt><rp>）</rp></ruby>ー<ruby><rb>雲</rb><rp>（</rp><rt>くも</rt><rp>）</rp></ruby>のかよ<ruby><rb>ひ</rb><rp>（</rp><rt>い</rt><rp>）</rp><rb>路</rb><rp>（</rp><rt>じ</rt><rp>）</rp></ruby>ー<br>　　　　　　<ruby><rb>吹</rb><rp>（</rp><rt>ふ</rt><rp>）</rp></ruby>きと<ruby><rb>ぢ</rb><rp>（</rp><rt>じ</rt><rp>）</rp></ruby>ーよー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>を</rb><rp>（</rp><rt>お</rt><rp>）</rp></ruby>とめのー<ruby><rb>姿</rb><rp>（</rp><rt>すがた</rt><rp>）</rp></ruby>ー<br>　　　しばしとどーめ<ruby><rb>む</rb><rp>（</rp><rt>ん</rt><rp>）</rp></ruby>ー</label>",
    },
    {
        no:   7,
        left: "ケ",
        center: "ス",
        right: "ハ",
        initial: "あ",
        kimariji: "あまの",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>天</rb><rp>（</rp><rt>あま</rt><rp>）</rp></ruby>の</font><ruby><rb>原</rb><rp>（</rp><rt>はら</rt><rp>）</rp></ruby>ーふりさけ<ruby><rb>見</rb><rp>（</rp><rt>み</rt><rp>）</rp></ruby>ればー<br>　　　　　　<ruby><rb>春</rb><rp>（</rp><rt>かす</rt><rp>）</rp><rb>日</rb><rp>（</rp><rt>が</rt><rp>）</rp></ruby>ーなるー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>三</rb><rp>（</rp><rt>み</rt><rp>）</rp><rb>笠</rb><rp>（</rp><rt>かさ</rt><rp>）</rp></ruby>のー<ruby><rb>山</rb><rp>（</rp><rt>やま</rt><rp>）</rp></ruby>にー<br>　　　<ruby><rb>出</rb><rp>（</rp><rt>い</rt><rp>）</rp></ruby>でし<ruby><rb>月</rb><rp>（</rp><rt>つき</rt><rp>）</rp></ruby>ーかもー</label>",
    },
    {
        no:  58,
        left: "オ",
        center: "ス",
        right: "ニ",
        initial: "あ",
        kimariji: "ありま",
        kaminoku: "<label for='fuda'><font color='red'>ありま</font><ruby><rb>山</rb><rp>（</rp><rt>やま</rt><rp>）</rp></ruby>ー<ruby><rb>ゐ</rb><rp>（</rp><rt>い</rt><rp>）</rp></ruby>なの<ruby><rb>笹</rb><rp>（</rp><rt>ささ</rt><rp>）</rp><rb>原</rb><rp>（</rp><rt>はら</rt><rp>）</rp></ruby>ー<br>　　　　　　<ruby><rb>風</rb><rp>（</rp><rt>かぜ</rt><rp>）</rp><rb>吹</rb><rp>（</rp><rt>ふ</rt><rp>）</rp></ruby>けーばー</label>",
        shimonoku: "<label for='fuda'>いでそよー<ruby><rb>人</rb><rp>（</rp><rt>ひと</rt><rp>）</rp></ruby>をー<br>　　　<ruby><rb>忘</rb><rp>（</rp><rt>わす</rt><rp>）</rp></ruby>れや<ruby><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ーするー</label>",
    },
    {
        no:  30,
        left: "コ",
        center: "ト",
        right: "ナ",
        initial: "あ",
        kimariji: "ありあ",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>有</rb><rp>（</rp><rt>あり</rt><rp>）</rp></ruby>あ</font>けのーつれなく<ruby><rb>見</rb><rp>（</rp><rt>み</rt><rp>）</rp></ruby>えしー<br>　　　　　　<ruby><rb>別</rb><rp>（</rp><rt>わか</rt><rp>）</rp></ruby>れーよりー</label>",
        shimonoku: "<label for='fuda'>あかつきーばかりー<br>　　　<ruby><rb>憂</rb><rp>（</rp><rt>う</rt><rp>）</rp></ruby>きもの<ruby><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ーなしー</label>",
    },
    {
        no:  39,
        left: "ア",
        center: "タ",
        right: "ホ",
        initial: "あ",
        kimariji: "あさじ",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>浅茅</rb><rp>（</rp><rt>あさじ</rt><rp>）</rp></ruby></font><ruby><rb>生</rb><rp>（</rp><rt>(う)</rt><rp>）</rp></ruby>のー<ruby><rb>小</rb><rp>（</rp><rt>お</rt><rp>）</rp><rb>野</rb><rp>（</rp><rt>の</rt><rp>）</rp></ruby>の<ruby><rb>篠</rb><rp>（</rp><rt>しの</rt><rp>）</rp><rb>原</rb><rp>（</rp><rt>はら</rt><rp>）</rp></ruby>ー<br>　　　　　　しのぶれーどー</label>",
        shimonoku: "<label for='fuda'>あまりてーなどかー<br>　　　<ruby><rb>人</rb><rp>（</rp><rt>ひと</rt><rp>）</rp></ruby>の<ruby><rb>恋</rb><rp>（</rp><rt>こい</rt><rp>）</rp></ruby>ーしきー</label>",
    },
    {
        no:  31,
        left: "キ",
        center: "シ",
        right: "フ",
        initial: "あ",
        kimariji: "あさ・あ",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>朝</rb><rp>（</rp><rt>あさ</rt><rp>）</rp></ruby>ぼらけあ</font>り<ruby><rb>明</rb><rp>（</rp><rt>あけ</rt><rp>）</rp></ruby>のー<ruby><rb>月</rb><rp>（</rp><rt>つき</rt><rp>）</rp></ruby>とー<br>　　　　　　<ruby><rb>見</rb><rp>（</rp><rt>み</rt><rp>）</rp></ruby>るまでーにー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>吉</rb><rp>（</rp><rt>よし</rt><rp>）</rp><rb>野</rb><rp>（</rp><rt>の</rt><rp>）</rp></ruby>のー<ruby><rb>里</rb><rp>（</rp><rt>さと</rt><rp>）</rp></ruby>にー<br>　　　<ruby><rb>降</rb><rp>（</rp><rt>ふ</rt><rp>）</rp></ruby>れる<ruby><rb>白</rb><rp>（</rp><rt>しら</rt><rp>）</rp></ruby>ー<ruby><rb>雪</rb><rp>（</rp><rt>ゆき</rt><rp>）</rp></ruby>ー</label>",
    },
    {
        no:  64,
        left: "コ",
        center: "サ",
        right: "ハ",
        initial: "あ",
        kimariji: "あさ・う",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>朝</rb><rp>（</rp><rt>あさ</rt><rp>）</rp></ruby>ぼらけ<ruby><rb>宇</rb><rp>（</rp><rt>う</rt><rp>）</rp></ruby></font><ruby><rb>治</rb><rp>（</rp><rt>じ</rt><rp>）</rp></ruby>のー<ruby><rb>川</rb><rp>（</rp><rt>かわ</rt><rp>）</rp><rb>霧</rb><rp>（</rp><rt>ぎり</rt><rp>）</rp></ruby>ー<br>　　　　　　<ruby><rb>絶</rb><rp>（</rp><rt>た</rt><rp>）</rp></ruby>え<ruby><rb>絶</rb><rp>（</rp><rt>だ</rt><rp>）</rp></ruby>えーにー</label>",
        shimonoku: "<label for='fuda'>あら<ruby><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>れーわたるー<br>　　　<ruby><rb>瀬</rb><rp>（</rp><rt>せ</rt><rp>）</rp><rb>々</rb><rp>（</rp><rt>ぜ</rt><rp>）</rp></ruby>のあじーろ<ruby><rb>木</rb><rp>（</rp><rt>ぎ</rt><rp>）</rp></ruby>ー</label>",
    },
    {
        no:   3,
        left: "カ",
        center: "ツ",
        right: "ニ",
        initial: "あ",
        kimariji: "あし",
        kaminoku: "<label for='fuda'><font color='red'>あし</font>びきのー<ruby><rb>山</rb><rp>《</rp><rt>やま</rt><rp>》</rp></ruby><ruby><rb>鳥</rb><rp>《</rp><rt>どり</rt><rp>》</rp></ruby>の<ruby><rb>尾</rb><rp>《</rp><rt>お</rt><rp>》</rp></ruby>のー<br>　　　　　　しだり<ruby><rb>尾</rb><rp>《</rp><rt>お</rt><rp>》</rp></ruby>ーのー</label>",
        shimonoku: "<label for='fuda'>ながながしー<ruby><rb>夜</rb><rp>《</rp><rt>よ</rt><rp>》</rp></ruby>をー<br>　　　ひとりかもー<ruby><rb>寝</rb><rp>《</rp><rt>ね</rt><rp>》</rp></ruby><ruby><rb>む</rb><rp>《</rp><rt>ん</rt><rp>》</rp></ruby>ー</label>",
    },
    {
        no:  43,
        left: "ケ",
        center: "チ",
        right: "ヌ",
        initial: "あ",
        kimariji: "あい",
        kaminoku: "<label for='fuda'><font color='red'>あ<ruby><rb>ひ</rb><rp>（</rp><rt>い</rt><rp>）</rp></ruby></font>みてのー<ruby><rb>後</rb><rp>（</rp><rt>のち</rt><rp>）</rp></ruby>の<ruby><rb>心</rb><rp>（</rp><rt>こころ</rt><rp>）</rp></ruby>にー<br>　　　　　　くらぶれーばー</label>",
        shimonoku: "<label for='fuda'><ruby><rb>昔</rb><rp>（</rp><rt>むかし</rt><rp>）</rp><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ー<ruby><rb>物</rb><rp>（</rp><rt>もの</rt><rp>）</rp></ruby>をー<br>　　　<ruby><rb>思</rb><rp>（</rp><rt>おも</rt><rp>）</rp><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ざりーけりー</label>",
    },
    {
        no:  52,
        left: "エ",
        center: "サ",
        right: "ノ",
        initial: "あ",
        kimariji: "あけ",
        kaminoku: "<label for='fuda'><font color='red'><ruby><rb>明</rb><rp>（</rp><rt>あ</rt><rp>）</rp></ruby>け</font>ぬればー<ruby><rb>暮</rb><rp>（</rp><rt>く</rt><rp>）</rp></ruby>るるものと<ruby><rb>は</rb><rp>（</rp><rt>わ</rt><rp>）</rp></ruby>ー<br>　　　　　　<ruby><rb>知</rb><rp>（</rp><rt>し</rt><rp>）</rp></ruby>りながーらー</label>",
        shimonoku: "<label for='fuda'>な<ruby><rb>ほ</rb><rp>（</rp><rt>お</rt><rp>）</rp></ruby>ー<ruby><rb>恨</rb><rp>（</rp><rt>うら</rt><rp>）</rp></ruby>めしきー<br>　　　<ruby><rb>朝</rb><rp>（</rp><rt>あさ</rt><rp>）</rp></ruby>ぼらけーかなー</label>",
    },
    {
        no: 101,
        left: null,
        center: null,
        right: null,
        initial: "",
        kimariji: "",
        kaminoku: "<span class='num'>終了</span><label for='fuda'>おわり</label>",
        shimonoku: "",
    }
];
